const HARD_LIST = [
    { id: "M1", name: "バーシャ", type: "メギド", isMajor: false, hint: "", officialName: "バーシャ", source: "ビフロンスキャラスト" },
    { id: "M2", name: "バルバリッサ", type: "メギド", isMajor: true, hint: "サタン派の結構えらいメギド。ソロモン誘拐事件の首謀者", officialName: "バルバリッサ", source: "暴走少女と一つ目幻獣の島 (他5)" },
    { id: "M3", name: "カーラ", type: "メギド", isMajor: false, hint: "", officialName: "カーラ", source: "アガリアレプトキャラスト (他1)" },
    { id: "M4", name: "シアエガ", type: "メギド", isMajor: false, hint: "", officialName: "シアエガ", source: "アリトンキャラスト" },
    { id: "M5", name: "イゴールナク", type: "メギド", isMajor: false, hint: "", officialName: "イゴールナク", source: "アリトンキャラスト" },
    { id: "M6", name: "アナキス", type: "メギド", isMajor: true, hint: "寄生メギド。", officialName: "アナキス", source: "サラキャラスト (他15)" },
    { id: "M7", name: "ストリガ", type: "メギド", isMajor: true, hint: "プルフラスやスコルベノトの元上官。メギドができている。", officialName: "軍団長ストリガ", source: "プルフラス・復讐の白百合 (他4)" },
    { id: "M8", name: "アシュレイ", type: "メギド", isMajor: true, hint: "研究者メギド。", officialName: "アシュレイ", source: "プルフラス・復讐の白百合 (他4)" },
    { id: "M9", name: "リビコ", type: "メギド", isMajor: true, hint: "サタナキアやアシュレイに研究をさせていた。", officialName: "軍団長リビコ", source: "プルフラス・復讐の白百合 (他2)" },
    { id: "M10", name: "バイアン", type: "メギド", isMajor: false, hint: "", officialName: "バイアン", source: "プルフラスキャラスト" },
    { id: "M11", name: "ケリコフ", type: "メギド", isMajor: false, hint: "", officialName: "ケリコフ", source: "プルフラスキャラスト (他1)" },
    { id: "M12", name: "フェルミ", type: "メギド", isMajor: false, hint: "", officialName: "フェルミ", source: "ジニマルキャラスト (他2)" },
    { id: "M13", name: "ヒューガル", type: "メギド", isMajor: false, hint: "", officialName: "ヒューガル", source: "ジニマルキャラスト (他2)" },
    { id: "M14", name: "ライカ", type: "メギド", isMajor: false, hint: "", officialName: "ライカ", source: "アマイモンキャラスト" },
    { id: "M15", name: "イグニス", type: "メギド", isMajor: false, hint: "", officialName: "イグニスってヤツ", source: "プロメテウスキャラスト" },
    { id: "M16", name: "カソグサ", type: "メギド", isMajor: true, hint: "マルバスの大事な友達。追放された。", officialName: "カソグサ", source: "マルバスRキャラスト (他2)" },
    { id: "M17", name: "アドラメレク", type: "メギド", isMajor: true, hint: "フォトン奪取が有効。覚醒減少も有効。", officialName: "アドラメレク", source: "6章 ヴァイガルド防衛線 2節 (他3)" },
    { id: "M18", name: "アリキノ", type: "メギド", isMajor: false, hint: "", officialName: "アリキノ", source: "キミに捧げし大地のソナタ (他1)" },
    { id: "M19", name: "ドラギナッツオ", type: "メギド", isMajor: true, hint: "懲罰局所属。フォトンインパルスと火属性攻撃をしてくる。", officialName: "ドラギナッツオ", source: "サタナイルキャラスト (他1)" },
    { id: "M20", name: "セメルーゼ", type: "メギド", isMajor: true, hint: "不沈軍団マモランティス所属。", officialName: "軍団長セメルーゼ", source: "6章 ヴァイガルド防衛線 3節" },
    { id: "M21", name: "サブブカ", type: "メギド", isMajor: true, hint: "不沈軍団マモランティス所属。", officialName: "軍団副官サブブカ", source: "6章 ヴァイガルド防衛線 3節" },
    { id: "M22", name: "メンドーサ", type: "メギド", isMajor: true, hint: "不沈軍団マモランティス所属。", officialName: "侵略魔兵メンドーサ", source: "6章 ヴァイガルド防衛線 3節" },
    { id: "M23", name: "ツギガル", type: "メギド", isMajor: true, hint: "不沈軍団マモランティス所属。", officialName: "侵略魔兵ツギガル", source: "6章 ヴァイガルド防衛線 3節" },
    { id: "M24", name: "アキレテス", type: "メギド", isMajor: false, hint: "不沈軍団マモランティス所属。", officialName: "侵略魔兵アキレテス", source: "6章 ヴァイガルド防衛線 3節" },
    { id: "M25", name: "ボヤーク", type: "メギド", isMajor: false, hint: "不沈軍団マモランティス所属。", officialName: "侵略魔兵ボヤーク", source: "6章 ヴァイガルド防衛線 3節" },
    { id: "M26", name: "ケイカ", type: "メギド", isMajor: false, hint: "不沈軍団マモランティス所属。", officialName: "侵略魔兵ケイカ", source: "6章 ヴァイガルド防衛線 3節" },
    { id: "M27", name: "ナランゾン", type: "メギド", isMajor: false, hint: "不沈軍団マモランティス所属。", officialName: "侵略魔兵ナランゾン", source: "6章 ヴァイガルド防衛線 3節" },
    { id: "M28", name: "マラコーダ", type: "メギド", isMajor: true, hint: "ヒュトギンの元上官。", officialName: "マラコーダ", source: "その交渉は平和のために (他3)" },
    { id: "M29", name: "カルカ", type: "メギド", isMajor: false, hint: "", officialName: "カルカ", source: "ヒュトギンキャラスト (他2)" },
    { id: "M30", name: "チリアット", type: "メギド", isMajor: true, hint: "べバルやアバラムの元上官。", officialName: "チリアット", source: "見習い女王と筋肉の悪魔 (他4)" },
    { id: "M31", name: "シオハオ", type: "メギド", isMajor: true, hint: "アスラフィルの監視役。リャナンシィとは子育て旅団が同じ。", officialName: "シオハオ", source: "アスラフィルキャラスト (他1)" },
    { id: "M32", name: "イオド", type: "メギド", isMajor: true, hint: "アクィエルと再戦の誓いをした。レナトゥスで魂を混ぜられた。", officialName: "イオド", source: "魔獅子と聖女と吸血鬼 (他1)" },
    { id: "M33", name: "アザト", type: "メギド", isMajor: false, hint: "", officialName: "アザト", source: "アクィエルキャラスト" },
    { id: "M34", name: "ギガス", type: "メギド", isMajor: true, hint: "死を招く邪本を著した。", officialName: "ギガス", source: "死を招く邪本ギギガガス" },
    { id: "M35", name: "ウィチセ", type: "メギド", isMajor: true, hint: "罵美優蛇総長。", officialName: "ウィチセ", source: "7章 メギドラル潜入 2節 (他4)" },
    { id: "M36", name: "ハヤイカ", type: "メギド", isMajor: true, hint: "罵美優蛇所属。", officialName: "ハヤイカ", source: "7章 メギドラル潜入 2節 (他4)" },
    { id: "M37", name: "クツロギン", type: "メギド", isMajor: true, hint: "くつろいでいた。", officialName: "クツロギン", source: "7章 メギドラル潜入 2節 (他2)" },
    { id: "M38", "name": "タシード", type: "メギド", isMajor: false, hint: "番魚はどうしたか尋ねた。", officialName: "タシード", source: "7章 メギドラル潜入 2節 (他2)" },
    { id: "M39", "name": "カイル", type: "メギド", isMajor: true, hint: "罵美優蛇元副総長。全体化を全体化する。", officialName: "カイル", source: "7章 メギドラル潜入 2節 (他6)" },
    { id: "M40", "name": "バレリコ", type: "メギド", isMajor: false, hint: "", officialName: "バレリコ", source: "オリエンスキャラスト (他7)" },
    { id: "M41", "name": "トリゲン", type: "メギド", isMajor: false, hint: "", officialName: "トリゲン", source: "オリエンスキャラスト (他7)" },
    { id: "M42", "name": "ハンミー", type: "メギド", isMajor: false, hint: "", officialName: "ハンミー", source: "オリエンスキャラスト (他7)" },
    { id: "M43", "name": "グンシー", type: "メギド", isMajor: false, hint: "", officialName: "参謀グンシー", source: "オリエンスキャラスト (他7)" },
    { id: "M44", "name": "アタッカス", type: "メギド", isMajor: false, hint: "", officialName: "チリアット軍団アタッカス", source: "オリエンスキャラスト" },
    { id: "M45", "name": "カバウス", type: "メギド", isMajor: false, hint: "", officialName: "チリアット軍団カバウス", source: "オリエンスキャラスト" },
    { id: "M46", "name": "ベロバッカ", type: "メギド", isMajor: false, hint: "", officialName: "軍団長ベロバッカ", source: "美味礼讃ノ魔宴 前編 (他2)" },
    { id: "M47", "name": "ホルン", type: "メギド", isMajor: true, hint: "ゲートを拡張する能力をもつ。励起で連続攻撃してくる。", officialName: "ホルン", source: "7章 メギドラル潜入 3節" },
    { id: "M48", "name": "アッキピテル", type: "メギド", isMajor: true, hint: "バラムの元部下。", officialName: "アッキピテル", source: "7章 メギドラル潜入 3節" },
    { id: "M49", "name": "カドワッカ", type: "メギド", isMajor: false, hint: "", officialName: "カドワッカ", source: "ニバスBキャラスト" },
    { id: "M50", "name": "サライ", type: "メギド", isMajor: false, hint: "", officialName: "サライ", source: "ニバスBキャラスト" },
    { id: "M51", "name": "リモウム", type: "メギド", isMajor: false, hint: "", officialName: "リモウム", source: "サタナキアBキャラスト (他1)" },
    { id: "M52", "name": "ブライ", type: "メギド", isMajor: false, hint: "", officialName: "ブライ", source: "サタナキアBキャラスト (他1)" },
    { id: "M53", "name": "アブナ", type: "メギド", isMajor: false, hint: "", officialName: "アブナ", source: "サタナキアBキャラスト (他1)" },
    { id: "M54", "name": "リリャナンシィ", type: "メギド", isMajor: true, hint: "ガンコナーの弟子。", officialName: "リリャナンシィ", source: "師の想い、弟子の想い" },
    { id: "M55", "name": "ガンコナー", type: "メギド", isMajor: true, hint: "アマゼロトに殺害された。寄生幻獣パラジスを発見した。", officialName: "ガンコナー", source: "師の想い、弟子の想い (他1)" },
    { id: "M56", "name": "ハイザーン", type: "メギド", isMajor: false, hint: "", officialName: "軍団長ハイザーン", source: "フルフルCキャラスト" },
    { id: "M57", "name": "イメーツ", type: "メギド", isMajor: false, hint: "", officialName: "副官イメーツ", source: "フルフルCキャラスト" },
    { id: "M58", "name": "カナッゾ", type: "メギド", isMajor: false, hint: "", officialName: "軍団長カナッゾ", source: "フルフルCキャラスト" },
    { id: "M59", "name": "ザリチェ", type: "メギド", isMajor: false, hint: "", officialName: "ザリチェ", source: "ユフィールCキャラスト" },
    { id: "M60", "name": "ドゥルジ", type: "メギド", isMajor: false, hint: "", officialName: "ドゥルジ", source: "ユフィールCキャラスト" },
    { id: "M61", "name": "リコレッキ", type: "メギド", isMajor: true, hint: "", officialName: "リコレッキ", source: "8章 第三計画 1節" },
    { id: "M62", "name": "テガツメ", type: "メギド", isMajor: true, hint: "手が爪っぽい。", officialName: "侵略兵テガツメ", source: "不死の幻獣と失いし過去" },
    { id: "M63", "name": "アカゲイ", type: "メギド", isMajor: true, hint: "赤毛っぽい。", officialName: "侵略兵アカゲイ", source: "不死の幻獣と失いし過去" },
    { id: "M64", "name": "ボッチキス", type: "メギド", isMajor: false, hint: "", officialName: "ボッチキス", source: "8章 第三計画 2節" },
    { id: "M65", "name": "ムオデル", type: "メギド", isMajor: false, hint: "", officialName: "ムオデル", source: "知の幻獣と悲しき対話 (他1)" },
    { id: "M66", "name": "ブリナ", type: "メギド", isMajor: false, hint: "", officialName: "ブリナ", source: "知の幻獣と悲しき対話 (他1)" },
    { id: "M67", "name": "ストレピ", type: "メギド", isMajor: false, hint: "", officialName: "ストレピ", source: "ダンタリオンRキャラスト" },
    { id: "M68", "name": "ロンガ", type: "メギド", isMajor: false, hint: "", officialName: "ロンガ", source: "ダンタリオンRキャラスト" },
    { id: "M69", "name": "ゲケン", type: "メギド", isMajor: false, hint: "", officialName: "ゲケン", source: "ダンタリオンRキャラスト" },
    { id: "M70", "name": "イステッカ", type: "メギド", isMajor: false, hint: "", officialName: "イステッカ", source: "ダンタリオンRキャラスト" },
    { id: "M71", "name": "コスーイ", type: "メギド", isMajor: false, hint: "", officialName: "コスーイ", source: "ベヒモスBキャラスト" },
    { id: "M72", "name": "モンジーン", type: "メギド", isMajor: false, hint: "", officialName: "モンジーン", source: "カジノ！―勝利の方程式― (他1)" },
    { id: "M73", "name": "スプリット", type: "メギド", isMajor: false, hint: "", officialName: "「カジノ」幹部スプリット", source: "カジノ！―勝利の方程式―" },
    { id: "M74", "name": "メリディアナ", type: "メギド", isMajor: false, hint: "", officialName: "メリディアナ", source: "カジノ！―勝利の方程式―" },
    { id: "M75", "name": "テゴワーイ", type: "メギド", isMajor: false, hint: "", officialName: "テゴワーイ", source: "グザファンキャラスト" },
    { id: "M76", "name": "タクラーム", type: "メギド", isMajor: false, hint: "", officialName: "タクラーム", source: "グザファンキャラスト" },
    { id: "M77", "name": "ソート", type: "メギド", isMajor: false, hint: "", officialName: "「カジノ」構成員ソート", source: "ミノソンキャラスト" },
    { id: "M78", "name": "ウーマ", type: "メギド", isMajor: false, hint: "", officialName: "「カジノ」構成員ウーマ", source: "ミノソンキャラスト" },
    { id: "M79", "name": "インガセクト", type: "メギド", isMajor: true, hint: "マモン親衛隊。使者ごときの分際で上に立とうとした。", officialName: "インガセクト", source: "8章 第三計画 3節 (他1)" },
    { id: "M80", "name": "ホーコック", type: "メギド", isMajor: false, hint: "", officialName: "ホーコック", source: "8章 第三計画 3節 (他1)" },
    { id: "M81", "name": "サンシタン", type: "メギド", isMajor: false, hint: "", officialName: "サンシタン", source: "暴走児バラキエル！" },
    { id: "M82", "name": "アヤトゥール", type: "メギド", isMajor: false, hint: "", officialName: "アヤトゥール", source: "暴走児バラキエル！" },
    { id: "M83", "name": "グローシタ", type: "メギド", isMajor: false, hint: "", officialName: "グローシタ", source: "暴走児バラキエル！" },
    { id: "M84", "name": "オーメニミル", type: "メギド", isMajor: false, hint: "", officialName: "軍団長オーメニミル", source: "暴走児バラキエル！ (他1)" },
    { id: "M85", "name": "タイガンニール", type: "メギド", isMajor: true, hint: "マモン親衛隊。対岸にいる。星間の塔にもいる。", officialName: "タイガンニール", source: "8章 第三計画 4節 (他3)" },
    { id: "M86", "name": "テッキトゥ", type: "メギド", isMajor: false, hint: "", officialName: "テッキトゥ", source: "マモンキャラスト" },
    { id: "M87", "name": "トークス", type: "メギド", isMajor: false, hint: "", officialName: "トークス", source: "マモンキャラスト" },
    { id: "M88", "name": "マテヨン", type: "メギド", isMajor: false, hint: "", officialName: "議会の騎士マテヨン", source: "メギドラルの悲劇の騎士" },
    { id: "M89", "name": "リリィ", type: "メギド", isMajor: false, hint: "夢見の者。", officialName: "リリィ", source: "メギドラルの悲劇の騎士" },
    { id: "M90", "name": "リリモ", type: "メギド", isMajor: false, hint: "夢見の者。", officialName: "リリモ", source: "メギドラルの悲劇の騎士" },
    { id: "M91", "name": "リリア", type: "メギド", isMajor: false, hint: "夢見の者。", officialName: "リリア", source: "メギドラルの悲劇の騎士" },
    { id: "M92", "name": "リリエ", type: "メギド", isMajor: false, hint: "夢見の者。", officialName: "リリエ", source: "メギドラルの悲劇の騎士" },
    { id: "M93", "name": "ナブール", type: "メギド", isMajor: false, hint: "", officialName: "ナブール", source: "恋は拷問、愛は処刑" },
    { id: "M94", "name": "モノバゾス", type: "メギド", isMajor: false, hint: "", officialName: "モノバゾス", source: "そして灯火は静かに消える" },
    { id: "M95", "name": "ジェヴォーダン", type: "メギド", isMajor: true, hint: "", officialName: "ジェヴォーダン", source: "そして灯火は静かに消える" },
    { id: "M96", "name": "ケーダシン", type: "メギド", isMajor: true, hint: "", officialName: "ケーダシン", source: "9章 懲罰局壊滅 1節 (他1)" },
    { id: "M97", "name": "オーシェ", type: "メギド", isMajor: false, hint: "", officialName: "オーシェ", source: "プルソンBキャラスト (他1)" },
    { id: "M98", "name": "ヨゴシ", type: "メギド", isMajor: false, hint: "", officialName: "ヨゴシ", source: "プルソンBキャラスト" },
    { id: "M99", "name": "マセタン", type: "メギド", isMajor: true, hint: "", officialName: "マセタン", source: "プルソンBキャラスト (他1)" },
    { id: "M100", "name": "トゥゲッチ", type: "メギド", isMajor: false, hint: "", officialName: "トゥゲッチ", source: "プルソンBキャラスト" },
    { id: "M101", "name": "コマルゼイ", type: "メギド", isMajor: false, hint: "", officialName: "コマルゼイ", source: "プルソンBキャラスト" },
    { id: "M102", "name": "シナナイン", type: "メギド", isMajor: true, hint: "", officialName: "シナナイン", source: "プルソンBキャラスト (他1)" },
    { id: "M103", "name": "クレンチン", type: "メギド", isMajor: false, hint: "", officialName: "クレンチン", source: "この手にかつての栄光を" },
    { id: "M104", "name": "ダイダロス", type: "メギド", isMajor: false, hint: "", officialName: "ダイダロス", source: "この手にかつての栄光を (他1)" },
    { id: "M105", "name": "ウボム", type: "メギド", isMajor: false, hint: "", officialName: "ウボム", source: "ブリフォーキャラスト" },
    { id: "M106", "name": "サンボーン", type: "メギド", isMajor: false, hint: "", officialName: "サンボーン", source: "ブリフォーキャラスト" },
    { id: "M107", "name": "ノーキン", type: "メギド", isMajor: false, hint: "", officialName: "ノーキン", source: "ブリフォーキャラスト" },
    { id: "M108", "name": "ヨワキム", type: "メギド", isMajor: false, hint: "", officialName: "ヨワキム", source: "ブリフォーキャラスト" },
    { id: "M109", "name": "ソレナリィ", type: "メギド", isMajor: false, hint: "", officialName: "ソレナリィ", source: "ブリフォーキャラスト" },
    { id: "M110", "name": "ソコソッコ", type: "メギド", isMajor: false, hint: "", officialName: "ソコソッコ", source: "ブリフォーキャラスト" },
    { id: "M111", "name": "メガイー", type: "メギド", isMajor: false, hint: "", officialName: "メガイー", source: "ブリフォーキャラスト" },
    { id: "M112", "name": "コザイク", type: "メギド", isMajor: false, hint: "", officialName: "コザイク", source: "ブリフォーキャラスト" },
    { id: "M113", "name": "ヤブレカブレ", type: "メギド", isMajor: true, hint: "", officialName: "ヤブレカブレ", source: "9章 懲罰局壊滅 2節 (他1)" },
    { id: "M114", "name": "サイゼン", type: "メギド", isMajor: false, hint: "", officialName: "サイゼン", source: "9章 懲罰局壊滅 2節 (他1)" },
    { id: "M115", "name": "ザミエル", type: "メギド", isMajor: false, hint: "", officialName: "ザミエル", source: "トーア公御前試合" },
    { id: "M116", "name": "ウゴーノシュ", type: "メギド", isMajor: false, hint: "", officialName: "ウゴーノシュ", source: "トーア公御前試合" },
    { id: "M117", "name": "ヒトカラゲ", type: "メギド", isMajor: false, hint: "", officialName: "ヒトカラゲ", source: "トーア公御前試合" },
    { id: "M118", "name": "メサジェ", type: "メギド", isMajor: false, hint: "", officialName: "メサジェ", source: "変わる心、変わらぬ心" },
    { id: "M119", "name": "エスピオン", type: "メギド", isMajor: false, hint: "", officialName: "エスピオン", source: "変わる心、変わらぬ心 (他2)" },
    { id: "M120", "name": "コローシャ", type: "メギド", isMajor: false, hint: "", officialName: "コローシャ", source: "変わる心、変わらぬ心" },
    { id: "M121", "name": "アッサシ", type: "メギド", isMajor: false, hint: "", officialName: "アッサシ", source: "変わる心、変わらぬ心" },
    { id: "M122", "name": "ラギル", type: "メギド", isMajor: false, hint: "", officialName: "ラギル", source: "変わる心、変わらぬ心 (他1)" },
    { id: "M123", "name": "ニーガス", type: "メギド", isMajor: false, hint: "", officialName: "ニーガス", source: "変わる心、変わらぬ心 (他1)" },
    { id: "M124", "name": "ガーディ", type: "メギド", isMajor: false, hint: "", officialName: "ガーディ", source: "アロケルRキャラスト" },
    { id: "M125", "name": "コゴトン", type: "メギド", isMajor: false, hint: "", officialName: "コゴトン", source: "其は素晴らしき戦士の器 (他1)" },
    { id: "M126", "name": "オキタエル", type: "メギド", isMajor: false, hint: "", officialName: "オキタエル", source: "険しく長き筋肉の道！" },
    { id: "M127", "name": "プルトン", type: "メギド", isMajor: true, hint: "異世界侵攻作戦総指揮官。", officialName: "プルトン", source: "9章 懲罰局壊滅 3節 (他10)" },
    { id: "M128", "name": "グウィルギィ", type: "メギド", isMajor: true, hint: "", officialName: "グウィルギィ", source: "WILD HUNT 前編 獣たちの集う場所 (他2)" },
    { id: "M129", "name": "エルドラコ", type: "メギド", isMajor: false, hint: "", officialName: "エルドラコ", source: "WILD HUNT 前編 獣たちの集う場所 (他2)" },
    { id: "M130", "name": "ハズサーン", type: "メギド", isMajor: false, hint: "", officialName: "ハズサーン", source: "WILD HUNT 前編 獣たちの集う場所 (他2)" },
    { id: "M131", "name": "ツガエル", type: "メギド", isMajor: false, hint: "", officialName: "ツガエル", source: "WILD HUNT 前編 獣たちの集う場所 (他2)" },
    { id: "M132", "name": "カカルドゥ", type: "メギド", isMajor: false, hint: "", officialName: "カカルドゥ", source: "WILD HUNT 前編 獣たちの集う場所 (他1)" },
    { id: "M133", "name": "イコロス", type: "メギド", isMajor: false, hint: "", officialName: "イコロス", source: "WILD HUNT 前編 獣たちの集う場所 (他2)" },
    { id: "M134", "name": "ギョフノリィ", type: "メギド", isMajor: false, hint: "", officialName: "ギョフノリィ", source: "WILD HUNT 前編 獣たちの集う場所" },
    { id: "M135", "name": "セイロンダガー", type: "メギド", isMajor: false, hint: "", officialName: "セイロンダガー", source: "ゲイボルグキャラスト" },
    { id: "M136", "name": "バントー", type: "メギド", isMajor: false, hint: "", officialName: "バントー", source: "商売人たちのブルース" },
    { id: "M137", "name": "グレシャム", type: "メギド", isMajor: true, hint: "", officialName: "グレシャム", source: "商売人たちのブルース (他1)" },
    { id: "M138", "name": "ドコミテン", type: "メギド", isMajor: false, hint: "", officialName: "ドコミテン", source: "商売人たちのブルース" },
    { id: "M139", "name": "ダレヤネン", type: "メギド", isMajor: false, hint: "", officialName: "ダレヤネン", source: "商売人たちのブルース" },
    { id: "M140", "name": "テダイ", type: "メギド", isMajor: false, hint: "", officialName: "テダイ", source: "商売人たちのブルース (他1)" },
    { id: "M141", "name": "オードル", type: "メギド", isMajor: false, hint: "", officialName: "オードル", source: "9章 懲罰局壊滅 4節" },
    { id: "M142", "name": "トーミル", type: "メギド", isMajor: false, hint: "", officialName: "トーミル", source: "9章 懲罰局壊滅 4節" },
    { id: "M143", "name": "ネブカドネザル", type: "メギド", isMajor: false, hint: "", officialName: "ネブカドネザル", source: "復讐の悪魔と怨讐の魔人" },
    { id: "M144", "name": "コシチェイ", type: "メギド", isMajor: true, hint: "", officialName: "コシチェイ", source: "アリオクキャラスト" },
    { id: "M145", "name": "ポベートール", type: "メギド", isMajor: false, hint: "", officialName: "ポベートール", source: "君はもう、1人じゃない" },
    { id: "M146", "name": "ファルファレロ", type: "メギド", isMajor: false, hint: "", officialName: "ファルファレロ", source: "君はもう、1人じゃない" },
    { id: "M147", "name": "エリク", type: "メギド", isMajor: false, hint: "", officialName: "エリク", source: "不死者バエルの切なる願い" },
    { id: "M148", "name": "ムチャリンダ", type: "メギド", isMajor: true, hint: "", officialName: "ムチャリンダ", source: "その優しさに意味がある (他8)" },
    { id: "M149", "name": "ギリメカラ", type: "メギド", isMajor: true, hint: "", officialName: "ギリメカラ", source: "彼の者、東方より来たり (他11)" },
    { id: "M150", "name": "マガツヒ", type: "メギド", isMajor: true, hint: "", officialName: "マガツヒ", source: "彼の者、東方より来たり (他11)" },
    { id: "M151", "name": "オズワリ", type: "メギド", isMajor: false, hint: "", officialName: "オズワリ", source: "10章 マグナ・レギオ 2節 (他1)" },
    { id: "M152", "name": "イキリオー", type: "メギド", isMajor: true, hint: "", officialName: "イキリオー", source: "10章 マグナ・レギオ 2節 (他1)" },
    { id: "M153", "name": "ドローヌマン", type: "メギド", isMajor: false, hint: "", officialName: "ドローヌマン", source: "10章 マグナ・レギオ 2節" },
    { id: "M154", "name": "アツメラルダ", type: "メギド", isMajor: false, hint: "", officialName: "アツメラルダ", source: "10章 マグナ・レギオ 2節" },
    { id: "M155", "name": "カタギ", type: "メギド", isMajor: false, hint: "", officialName: "カタギ", source: "10章 マグナ・レギオ 2節 (他3)" },
    { id: "M156", "name": "ワレェ", type: "メギド", isMajor: false, hint: "", officialName: "ワレェ", source: "10章 マグナ・レギオ 2節 (他3)" },
    { id: "M157", "name": "ニクー", type: "メギド", isMajor: false, hint: "", officialName: "ニクー", source: "10章 マグナ・レギオ 2節 (他1)" },
    { id: "M158", "name": "ダンセ", type: "メギド", isMajor: false, hint: "", officialName: "ダンセ", source: "10章 マグナ・レギオ 2節" },
    { id: "M159", "name": "シャドウギャクソン", type: "メギド", isMajor: false, hint: "", officialName: "シャドウギャクソン", source: "10章 マグナ・レギオ 2節 (他2)" },
    { id: "M160", "name": "インシュウ", type: "メギド", isMajor: false, hint: "", officialName: "インシュウ", source: "10章 マグナ・レギオ 2節 (他2)" },
    { id: "M161", "name": "ムーメン", type: "メギド", isMajor: false, hint: "", officialName: "ムーメン", source: "10章 マグナ・レギオ 2節" },
    { id: "M162", "name": "スマホミー", type: "メギド", isMajor: false, hint: "", officialName: "スマホミー", source: "10章 マグナ・レギオ 2節" },
    { id: "M163", "name": "アオリウンデ", type: "メギド", isMajor: false, hint: "", officialName: "アオリウンデ", source: "10章 マグナ・レギオ 2節 (他2)" },
    { id: "M164", "name": "ミマモラー", type: "メギド", isMajor: false, hint: "", officialName: "ミマモラー", source: "10章 マグナ・レギオ 2節" },
    { id: "M165", "name": "マッカーセイル", type: "メギド", isMajor: false, hint: "", officialName: "マッカーセイル", source: "10章 マグナ・レギオ 2節 (他1)" },
    { id: "M166", "name": "リバイバイル", type: "メギド", isMajor: true, hint: "", officialName: "リバイバイル", source: "10章 マグナ・レギオ 2節 (他10)" },
    { id: "M167", "name": "トメラニアン", type: "メギド", isMajor: false, hint: "", officialName: "トメラニアン", source: "10章 マグナ・レギオ 2節 (他3)" },
    { id: "M168", "name": "トビー", type: "メギド", isMajor: false, hint: "", officialName: "トビー", source: "10章 マグナ・レギオ 2節 (他4)" },
    { id: "M169", "name": "ハッタリッパー", type: "メギド", isMajor: false, hint: "", officialName: "ハッタリッパー", source: "10章 マグナ・レギオ 2節" },
    { id: "M170", "name": "シーネ", type: "メギド", isMajor: false, hint: "", officialName: "シーネ", source: "10章 マグナ・レギオ 2節 (他1)" },
    { id: "M171", "name": "オムカ", type: "メギド", isMajor: false, hint: "", officialName: "オムカ", source: "10章 マグナ・レギオ 2節" },
    { id: "M172", "name": "ネガティ", type: "メギド", isMajor: false, hint: "", officialName: "ネガティ", source: "10章 マグナ・レギオ 2節 (他2)" },
    { id: "M173", "name": "ズルコワルコ", type: "メギド", isMajor: true, hint: "", officialName: "ズルコワルコ", source: "10章 マグナ・レギオ 2節 (他1)" },
    { id: "M174", "name": "モドリー", type: "メギド", isMajor: false, hint: "", officialName: "モドリー", source: "10章 マグナ・レギオ 2節" },
    { id: "M175", "name": "シルバホン", type: "メギド", isMajor: false, hint: "", officialName: "シルバホン", source: "継承せし者たち (他5)" },
    { id: "M176", "name": "タイガーセンポ", type: "メギド", isMajor: true, hint: "", officialName: "タイガーセンポ", source: "継承せし者たち (他7)" },
    { id: "M177", "name": "ゲストレイス", type: "メギド", isMajor: false, hint: "", officialName: "ゲストレイス", source: "10章 マグナ・レギオ 3節 ステージ103 (他9)" },
    { id: "M178", "name": "プロセルピナ", type: "メギド", isMajor: true, hint: "", officialName: "プロセルピナ", source: "10章 マグナ・レギオ 3節 ステージ104 (他11)" },
    { id: "M179", "name": "ダイオーン", type: "メギド", isMajor: false, hint: "", officialName: "ダイオーン", source: "閉ざされた世界の中で" },
    { id: "M180", "name": "モンゴール", type: "メギド", isMajor: false, hint: "", officialName: "モンゴール", source: "閉ざされた世界の中で" },
    { id: "M181", "name": "ウェンディゴ", type: "メギド", isMajor: true, hint: "", officialName: "ウェンディゴ", source: "When'd he go into there？" },
    { id: "M182", "name": "ゼッコロ", type: "メギド", isMajor: false, hint: "", officialName: "ゼッコロ", source: "アスモデウスRキャラスト" },
    { id: "M183", "name": "ゴルドホン", type: "メギド", isMajor: false, hint: "", officialName: "ゴルドホン", source: "艶なる狐、夢のまにまに (他3)" },
    { id: "M184", "name": "センコック", type: "メギド", isMajor: false, hint: "", officialName: "センコック", source: "信頼と可能性" },
    { id: "M185", "name": "コーサラウ", type: "メギド", isMajor: false, hint: "", officialName: "コーサラウ", source: "信頼と可能性" },
    { id: "M186", "name": "ワラベトール", type: "メギド", isMajor: false, hint: "", officialName: "ワラベトール", source: "信頼と可能性" },
    { id: "M187", "name": "ニューカマ", type: "メギド", isMajor: false, hint: "", officialName: "ニューカマ", source: "ウァラクCキャラスト" },
    { id: "M188", "name": "シーニア", type: "メギド", isMajor: false, hint: "", officialName: "シーニア", source: "ウァラクCキャラスト" },
    { id: "M189", "name": "オネスト", type: "メギド", isMajor: false, hint: "", officialName: "オネスト", source: "ウァラクCキャラスト" },
    { id: "M190", "name": "ボヤクーナ", type: "メギド", isMajor: false, hint: "", officialName: "ボヤクーナ", source: "グレモリーRキャラスト" },
    { id: "M191", "name": "デスガ", type: "メギド", isMajor: false, hint: "", officialName: "デスガ", source: "グレモリーRキャラスト" },
    { id: "M192", "name": "ロックロー", type: "メギド", isMajor: false, hint: "", officialName: "ロックロー", source: "龍馬相搏、腥風不已 (他1)" },
    { id: "M193", "name": "ヒットバン", type: "メギド", isMajor: false, hint: "", officialName: "ヒットバン", source: "龍馬相搏、腥風不已 (他1)" },
    { id: "M194", "name": "ペナンガラン", type: "メギド", isMajor: false, hint: "", officialName: "ペナンガラン", source: "龍馬相搏、腥風不已 (他1)" },
    { id: "M195", "name": "ラーフ", type: "メギド", isMajor: false, hint: "", officialName: "ラーフ", source: "龍馬相搏、腥風不已 (他1)" },
    { id: "M196", "name": "ファンブラン", type: "メギド", isMajor: false, hint: "", officialName: "ファンブラン", source: "11章 激動のメギドラル 1節 ステージ109" },
    { id: "M197", "name": "ボロボロス", type: "メギド", isMajor: false, hint: "", officialName: "ボロボロス", source: "ソロモン王の日常・春" },
    { id: "M198", "name": "レオナール", type: "メギド", isMajor: true, hint: "", officialName: "レオナール", source: "11章 激動のメギドラル 1節 ステージ110 (他8)" },
    { id: "M199", "name": "ニョイフレッシュ", type: "メギド", isMajor: true, hint: "", officialName: "ニョイフレッシュ", source: "吼えよ、カクリヨの白い虎 (他6)" },
    { id: "M200", "name": "コスカライオン", type: "メギド", isMajor: false, hint: "", officialName: "コスカライオン", source: "吼えよ、カクリヨの白い虎 (他1)" },
    { id: "M201", "name": "ザコイヤ", type: "メギド", isMajor: false, hint: "", officialName: "ザコイヤ", source: "11章 激動のメギドラル 1節 ステージ111" },
    { id: "M202", "name": "ウニノセール", type: "メギド", isMajor: false, hint: "", officialName: "ウニノセール", source: "真味、ただこれ淡なれば" },
    { id: "M203", "name": "トリフマゼンタ", type: "メギド", isMajor: false, hint: "", officialName: "トリフマゼンタ", source: "真味、ただこれ淡なれば" },
    { id: "M204", "name": "アブラポス", type: "メギド", isMajor: false, hint: "", officialName: "アブラポス", source: "真味、ただこれ淡なれば" },
    { id: "M205", "name": "ショッパイン", type: "メギド", isMajor: false, hint: "", officialName: "ショッパイン", source: "真味、ただこれ淡なれば" },
    { id: "M206", "name": "ホイクイーン", type: "メギド", isMajor: false, hint: "", officialName: "ホイクイーン", source: "11章 激動のメギドラル 2節 ステージ112" },
    { id: "M207", "name": "ストゥム", type: "メギド", isMajor: true, hint: "", officialName: "ストゥム", source: "11章 激動のメギドラル 2節 ステージ112" },
    { id: "M208", "name": "ケノックス", type: "メギド", isMajor: false, hint: "", officialName: "ケノックス", source: "ソロモン王の日常・夏" },
    { id: "M209", "name": "ショックジョー", type: "メギド", isMajor: false, hint: "", officialName: "ショックジョー", source: "ソロモン王の日常・夏" },
    { id: "M210", "name": "セぷテントリオン", type: "メギド", isMajor: true, hint: "", officialName: "セぷテントリオン", source: "銃と私とあいつとそいつ" },
    { id: "M211", "name": "スジトゥス", type: "メギド", isMajor: false, hint: "", officialName: "スジトゥス", source: "銃と私とあいつとそいつ" },
    { id: "M212", "name": "ギリガティ", type: "メギド", isMajor: false, hint: "", officialName: "ギリガティ", source: "銃と私とあいつとそいつ" },
    { id: "M213", "name": "デミウルゴス", type: "メギド", isMajor: true, hint: "", officialName: "デミウルゴス", source: "11章 激動のメギドラル 2節 ステージ113 (他6)" },
    { id: "M214", "name": "チャラケル", type: "メギド", isMajor: false, hint: "", officialName: "チャラケル", source: "オリエンスBキャラスト" },
    { id: "M215", "name": "インフム", type: "メギド", isMajor: false, hint: "", officialName: "インフム", source: "オリエンスBキャラスト" },
    { id: "M216", "name": "ラッカン", type: "メギド", isMajor: false, hint: "", officialName: "ラッカン", source: "オリエンスBキャラスト" },
    { id: "M217", "name": "ガルデニング", type: "メギド", isMajor: true, hint: "", officialName: "ガルデニング", source: "食べて育てて分け合って" },
    { id: "M218", "name": "オハナヴァタケ", type: "メギド", isMajor: false, hint: "", officialName: "オハナヴァタケ", source: "食べて育てて分け合って" },
    { id: "M219", "name": "ヴィニルハウズ", type: "メギド", isMajor: false, hint: "", officialName: "ヴィニルハウズ", source: "食べて育てて分け合って" },
    { id: "M220", "name": "ファナティッカ", type: "メギド", isMajor: false, hint: "", officialName: "ファナティッカ", source: "11章 激動のメギドラル 3節 ステージ115" },
    { id: "M221", "name": "リリル", type: "メギド", isMajor: false, hint: "夢見のリリル", officialName: "リリル", source: "それは、逃れ得ぬ呪縛 (他2)" },
    { id: "M222", "name": "サラウンピョウ", type: "メギド", isMajor: false, hint: "", officialName: "サラウンピョウ", source: "それは、逃れ得ぬ呪縛" },
    { id: "M223", "name": "モノシリィ", type: "メギド", isMajor: false, hint: "", officialName: "モノシリィ", source: "母と子と、おかーさんと" },
    { id: "M224", "name": "クイークェグ", type: "メギド", isMajor: false, hint: "", officialName: "クイークェグ", source: "母と子と、おかーさんと" },
    { id: "M225", "name": "イシュメール", type: "メギド", isMajor: false, hint: "", officialName: "イシュメール", source: "母と子と、おかーさんと" },
    { id: "M226", "name": "エイハブ", type: "メギド", isMajor: true, hint: "", officialName: "エイハブ", source: "母と子と、おかーさんと" },
    { id: "M227", "name": "スターバック", type: "メギド", isMajor: true, hint: "", officialName: "スターバック", source: "母と子と、おかーさんと" },
    { id: "M228", "name": "タシュテゴ", type: "メギド", isMajor: false, hint: "", officialName: "タシュテゴ", source: "母と子と、おかーさんと" },
    { id: "M229", "name": "クジョコ", type: "メギド", isMajor: false, hint: "", officialName: "クジョコ", source: "ソロモン王の日常・冬" },
    { id: "M230", "name": "クサムシュリ", type: "メギド", isMajor: false, hint: "", officialName: "クサムシュリ", source: "11章 激動のメギドラル 4節 ステージ118" },
    { id: "M231", "name": "モーニゲル", type: "メギド", isMajor: false, hint: "", officialName: "モーニゲル", source: "11章 激動のメギドラル 4節 ステージ120" },
    { id: "M232", "name": "マモリキレン", type: "メギド", isMajor: false, hint: "防衛隊長マモリキレン", officialName: "マモリキレン", source: "帰らばや、我が故郷へ" },
    { id: "M233", "name": "トンデーン", type: "メギド", isMajor: false, hint: "", officialName: "トンデーン", source: "帰らばや、我が故郷へ" },
    { id: "M234", "name": "カイタック", type: "メギド", isMajor: false, hint: "", officialName: "カイタック", source: "帰らばや、我が故郷へ" },
    { id: "M235", "name": "ラプラス", type: "メギド", isMajor: true, hint: "", officialName: "ラプラス", source: "12章 そして世界が生まれる 1節 ステージ121 (他1)" },
    { id: "M236", "name": "ヤヌス", type: "メギド", isMajor: true, hint: "", officialName: "ヤヌス", source: "12章 そして世界が生まれる 1節 ステージ121 (他2)" },
    { id: "M237", "name": "ムコイコカ", type: "メギド", isMajor: false, hint: "", officialName: "ムコイコカ", source: "12章 そして世界が生まれる 1節 ステージ122 (他1)" },
    { id: "M238", "name": "アザメザラク", type: "メギド", isMajor: false, hint: "", officialName: "アザメザラク", source: "ソロモン王と呪いの人形" },
    { id: "M239", "name": "タスケネイ", type: "メギド", isMajor: false, hint: "", officialName: "タスケネイ", source: "サタンキャラスト" },
    { id: "M240", "name": "ゴルディン", type: "メギド", isMajor: false, hint: "", officialName: "ゴルディン", source: "12章 そして世界が生まれる 2節 ステージ125" },
    { id: "M241", "name": "パイロキシアン", type: "メギド", isMajor: true, hint: "", officialName: "パイロキシアン", source: "12章 そして世界が生まれる 2節 ステージ126" },
    { id: "M242", "name": "イクサシタ", type: "メギド", isMajor: false, hint: "", officialName: "イクサシタ", source: "12章 そして世界が生まれる 3節 ステージ127" },
    { id: "M243", "name": "ニューリアン", type: "メギド", isMajor: false, hint: "", officialName: "ニューリアン", source: "12章 そして世界が生まれる 3節 ステージ128 (他1)" },
    { id: "M244", "name": "シンクシング", type: "メギド", isMajor: false, hint: "", officialName: "シンクシング", source: "12章 そして世界が生まれる 3節 ステージ128 (他1)" },
    { id: "M245", "name": "ヤルーゼ", type: "メギド", isMajor: false, hint: "", officialName: "ヤルーゼ", source: "12章 そして世界が生まれる 3節 ステージ128 (他1)" },
    { id: "M246", "name": "オレンスバイ", type: "メギド", isMajor: false, hint: "", officialName: "オレンスバイ", source: "12章 そして世界が生まれる 3節 ステージ129" },
    { id: "M247", "name": "モードリタイン", type: "メギド", isMajor: false, hint: "", officialName: "モードリタイン", source: "エピローグ" },
    { id: "M248", "name": "ムボーダン", type: "メギド", isMajor: true, hint: "脳筋参謀メギド", officialName: "ムボーダン", source: "脳筋参謀メギド" },
    { id: "M249", "name": "アルスノヴァ", type: "メギド", isMajor: true, hint: "エルダー", officialName: "アルス・ノヴァ", source: "アルス・ノヴァ" },
    { id: "M250", "name": "エリダヌス", type: "メギド", isMajor: true, hint: "ザウラクたちの元になったメギド", officialName: "エリダヌス", source: "エリダヌス" },
    { id: "M251", "name": "ヒュプノス", type: "メギド", isMajor: false, hint: "", officialName: "ヒュプノス", source: "11章 激動のメギドラル 3節 ステージ117" },
    { id: "M252", "name": "メギラオン", type: "メギド", isMajor: false, hint: "サタンの取り巻き 002", officialName: "メギラオン", source: "メギラオン" },
    { id: "M253", "name": "トリギラン", type: "メギド", isMajor: false, hint: "サタンの取り巻き 003", officialName: "トリギラン", source: "トリギラン" },
    { id: "M254", "name": "アノウノン", type: "メギド", isMajor: true, hint: "メインクエスト・ステージ118 ぺクスにフォトンバーストしてたメギド", officialName: "アノウノン", source: "アノウノン" },
    { id: "M255", "name": "アカマル", type: "メギド", isMajor: true, hint: "メインクエスト・ステージ8 ゲートを守っていたメギド", officialName: "アカマル", source: "アカマル" },
    { id: "M256", "name": "クダクター", type: "メギド", isMajor: false, hint: "ホルンの取り巻き", officialName: "クダクター", source: "クダクター" },
    { id: "M257", "name": "ケズリナ", type: "メギド", isMajor: false, hint: "ホルンの取り巻き", officialName: "ケズリナ", source: "ケズリナ" },

    { id: "H1", name: "ガブリエル", type: "ハルマ", isMajor: true, hint: "", officialName: "ガブリエル", source: "1章 辺境の剣 (他52)" },
    { id: "H2", name: "カマエル", type: "ハルマ", isMajor: true, hint: "", officialName: "カマエル", source: "2章 王都の盾 (他46)" },
    { id: "H3", name: "ミカエル", type: "ハルマ", isMajor: true, hint: "", officialName: "ミカエル", source: "3章 赤い月 (他16)" },
    { id: "H4", name: "コロスエル", type: "ハルマ", isMajor: true, hint: "", officialName: "コロスエル", source: "10章 マグナ・レギオ 3節 ステージ105" },
    { id: "H5", name: "ヨリソエル", type: "ハルマ", isMajor: false, hint: "", officialName: "ヨリソエル", source: "10章 マグナ・レギオ 3節 ステージ105 (他6)" },
    { id: "H6", name: "パットキエル", type: "ハルマ", isMajor: true, hint: "", officialName: "パットキエル", source: "10章 マグナ・レギオ 3節 ステージ105" },
    { id: "H7", name: "ジットタエル", type: "ハルマ", isMajor: true, hint: "", officialName: "ジットタエル", source: "10章 マグナ・レギオ 3節 ステージ105" },
    { id: "H8", name: "テレルエル", type: "ハルマ", isMajor: false, hint: "", officialName: "テレルエル", source: "10章 マグナ・レギオ 3節 ステージ105" },
    { id: "H9", name: "キガエル", type: "ハルマ", isMajor: false, hint: "", officialName: "キガエル", source: "10章 マグナ・レギオ 3節 ステージ105 (他1)" },
    { id: "H10", name: "デテキエル", type: "ハルマ", isMajor: false, hint: "", officialName: "デテキエル", source: "10章 マグナ・レギオ 3節 ステージ105 (他1)" },
    { id: "H11", name: "フセギエル", type: "ハルマ", isMajor: false, hint: "", officialName: "フセギエル", source: "10章 マグナ・レギオ 4節 ステージ106" },
    { id: "H12", name: "スナッフエル", type: "ハルマ", isMajor: true, hint: "", officialName: "スナッフエル", source: "10章 マグナ・レギオ 4節 ステージ106" },
    { id: "H13", name: "サイコエル", type: "ハルマ", isMajor: false, hint: "", officialName: "サイコエル", source: "10章 マグナ・レギオ 4節 ステージ106 (他1)" },
    { id: "H14", name: "マテヨエル", type: "ハルマ", isMajor: true, hint: "", officialName: "マテヨエル", source: "10章 マグナ・レギオ 4節 ステージ106" },
    { id: "H15", name: "トラエル", type: "ハルマ", isMajor: false, hint: "", officialName: "トラエル", source: "アスモデウスRキャラスト" },
    { id: "H16", name: "ツタエル", type: "ハルマ", isMajor: false, hint: "", officialName: "ツタエル", source: "アスモデウスRキャラスト" },
    { id: "H17", name: "カゾエル", type: "ハルマ", isMajor: false, hint: "", officialName: "カゾエル", source: "アスモデウスRキャラスト" },
    { id: "H18", name: "タネウエル", type: "ハルマ", isMajor: false, hint: "", officialName: "タネウエル", source: "10章 マグナ・レギオ 4節 ステージ107" },
    { id: "H19", name: "イモフエル", type: "ハルマ", isMajor: false, hint: "", officialName: "イモフエル", source: "10章 マグナ・レギオ 4節 ステージ107" },
    { id: "H20", name: "ナベニエル", type: "ハルマ", isMajor: true, hint: "", officialName: "ナベニエル", source: "10章 マグナ・レギオ 4節 ステージ107" },
    { id: "H21", name: "アタマサエル", type: "ハルマ", isMajor: false, hint: "", officialName: "アタマサエル", source: "10章 マグナ・レギオ 4節 ステージ107" },
    { id: "H22", name: "ジンジャエル", type: "ハルマ", isMajor: true, hint: "", officialName: "ジンジャエル", source: "10章 マグナ・レギオ 4節 ステージ107" },
    { id: "H23", name: "シーゴッドオエル", type: "ハルマ", isMajor: true, hint: "", officialName: "シーゴッドオエル", source: "10章 マグナ・レギオ 4節 ステージ107 (他4)" },
    { id: "H24", name: "チャーリーデカエル", type: "ハルマ", isMajor: true, hint: "", officialName: "チャーリーデカエル", source: "10章 マグナ・レギオ 4節 ステージ107" },
    { id: "H25", name: "メッシクーエル", type: "ハルマ", isMajor: false, hint: "", officialName: "メッシクーエル", source: "10章 マグナ・レギオ 4節 ステージ107 (他1)" },
    { id: "H26", name: "フローネルエル", type: "ハルマ", isMajor: false, hint: "", officialName: "フローネルエル", source: "10章 マグナ・レギオ 4節 ステージ107" },
    { id: "H27", name: "ウテヌエル", type: "ハルマ", isMajor: false, hint: "", officialName: "ウテヌエル", source: "10章 マグナ・レギオ 4節 ステージ108" },
    { id: "H28", name: "マサカエル", type: "ハルマ", isMajor: true, hint: "", officialName: "マサカエル", source: "11章 激動のメギドラル 1節 ステージ111 (他1)" },
    { id: "H29", name: "モーカエル", type: "ハルマ", isMajor: true, hint: "", officialName: "モーカエル", source: "11章 激動のメギドラル 2節 ステージ113 (他4)" },
    { id: "H30", name: "マイゴエル", type: "ハルマ", isMajor: false, hint: "", officialName: "マイゴエル", source: "11章 激動のメギドラル 2節 ステージ113 (他2)" },
    { id: "H31", name: "ツカマエル", type: "ハルマ", isMajor: false, hint: "", officialName: "ツカマエル", source: "11章 激動のメギドラル 2節 ステージ113 (他3)" },
    { id: "H32", name: "ヨクミエル", type: "ハルマ", isMajor: false, hint: "", officialName: "ヨクミエル", source: "12章 そして世界が生まれる 1節 ステージ121 (他2)" },
    { id: "H33", name: "イマナライエル", type: "ハルマ", isMajor: true, hint: "", officialName: "イマナライエル", source: "12章 そして世界が生まれる 2節 ステージ124 (他1)" },
    { id: "H34", name: "ウタガエル", type: "ハルマ", isMajor: false, hint: "", officialName: "ウタガエル", source: "12章 そして世界が生まれる 3節 ステージ127" },
    { id: "H35", name: "カンガエル", type: "ハルマ", isMajor: false, hint: "", officialName: "カンガエル", source: "12章 そして世界が生まれる 3節 ステージ127" },
    { id: "H36", name: "マチガエル", type: "ハルマ", isMajor: false, hint: "", officialName: "マチガエル", source: "8魔星モレク、参戦" },
    { id: "H37", name: "マダタタカエル", type: "ハルマ", isMajor: false, hint: "", officialName: "マダタタカエル", source: "8魔星モレク、参戦" },
    { id: "H38", name: "ヒックリカエル", type: "ハルマ", isMajor: false, hint: "", officialName: "ヒックリカエル", source: "8魔星モレク、参戦" },
    { id: "H39", name: "サガシエル", type: "ハルマ", isMajor: false, hint: "", officialName: "サガシエル", source: "エピローグ" },
    { id: "H40", name: "ラジエル", type: "ハルマ", isMajor: true, hint: "", officialName: "ラジエル", source: "エピローグ" }
];
