const HARD_LIST = [
    { id: "M1", name: "バーシャ", type: "メギド", isMajor: false, hints: [], officialName: "バーシャ", source: "ビフロンスキャラスト" },
    { id: "M2", name: "バルバリッサ", type: "メギド", isMajor: true, hints: ["サタン派の結構えらいメギド。", "ソロモン誘拐事件の首謀者。", "おそらく元ネタはダンテの「神曲」の悪魔"], officialName: "バルバリッサ", source: "暴走少女と一つ目幻獣の島 (他5)" },
    { id: "M3", name: "カーラ", type: "メギド", isMajor: false, hints: [], officialName: "カーラ", source: "アガリアレプトキャラスト (他1)" },
    { id: "M4", name: "シアエガ", type: "メギド", isMajor: false, hints: ["拒絶区画の一部で領主をしていたメギド。", "かつてアリトンが仕えていた。", "おそらく元ネタはクトゥルフ神話"], officialName: "シアエガ", source: "アリトンキャラスト" },
    { id: "M5", name: "イゴールナク", type: "メギド", isMajor: false, hints: ["おそらく元ネタはクトゥルフ神話"], officialName: "イゴールナク", source: "アリトンキャラスト" },
    { id: "M6", name: "アナキス", type: "メギド", isMajor: true, hints: ["寄生メギド。"], officialName: "アナキス", source: "サラキャラスト (他15)" },
    { id: "M7", name: "ストリガ", type: "メギド", isMajor: true, hints: ["プルフラスやスコルベノトの元上官。", "メギドができている。", "おそらく元ネタはルーマニア伝承。"], officialName: "軍団長ストリガ", source: "プルフラス・復讐の白百合 (他4)" },
    { id: "M8", name: "アシュレイ", type: "メギド", isMajor: true, hints: ["リビコの部下。", "寄生メギドアナキスの研究をしていた。"], officialName: "アシュレイ", source: "プルフラス・復讐の白百合 (他4)" },
    { id: "M9", name: "リビコ", type: "メギド", isMajor: true, hints: ["サタナキアやアシュレイに研究をさせていた。", "議席持ち", "おそらく元ネタはダンテの「神曲」の悪魔"], officialName: "軍団長リビコ", source: "プルフラス・復讐の白百合 (他2)" },
    { id: "M10", name: "バイアン", type: "メギド", isMajor: false, hints: [], officialName: "バイアン", source: "プルフラスキャラスト" },
    { id: "M11", name: "ケリコフ", type: "メギド", isMajor: false, hints: [], officialName: "ケリコフ", source: "プルフラスキャラスト (他1)" },
    { id: "M12", name: "フェルミ", type: "メギド", isMajor: false, hints: [], officialName: "フェルミ", source: "ジニマルキャラスト (他2)" },
    { id: "M13", name: "ヒューガル", type: "メギド", isMajor: false, hints: [], officialName: "ヒューガル", source: "ジニマルキャラスト (他2)" },
    { id: "M14", name: "ライカ", type: "メギド", isMajor: false, hints: [], officialName: "ライカ", source: "アマイモンキャラスト" },
    { id: "M15", name: "イグニス", type: "メギド", isMajor: false, hints: [], officialName: "イグニスってヤツ", source: "プロメテウスキャラスト" },
    { id: "M16", name: "カソグサ", type: "メギド", isMajor: true, hints: ["マルバスの大事な友達。", "追放された。", "おそらく元ネタはクトゥルフ神話"], officialName: "カソグサ", source: "マルバスRキャラスト (他2)" },
    { id: "M17", name: "アドラメレク", type: "メギド", isMajor: true, hints: ["アジトを襲撃した。", "フォトン奪取が有効。覚醒減少も有効。", "地獄の辞典にその名前の記載がある。"], officialName: "アドラメレク", source: "6章 ヴァイガルド防衛線 2節 (他3)" },
    { id: "M18", name: "アリキノ", type: "メギド", isMajor: false, hints: ["サタナイルの元部下。", "おそらく元ネタはダンテの「神曲」の悪魔"], officialName: "アリキノ", source: "キミに捧げし大地のソナタ (他1)" },
    { id: "M19", name: "ドラギナッツオ", type: "メギド", isMajor: true, hints: ["懲罰局所属。", "フォトンインパルスと火属性攻撃をしてくる。", "おそらく元ネタはダンテの「神曲」の悪魔"], officialName: "ドラギナッツオ", source: "サタナイルキャラスト (他1)" },
    { id: "M20", name: "セメルーゼ", type: "メギド", isMajor: true, hints: ["不沈軍団マモランティス所属。", "議席もち。"], officialName: "軍団長セメルーゼ", source: "6章 ヴァイガルド防衛線 3節" },
    { id: "M21", name: "サブブカ", type: "メギド", isMajor: true, hints: ["不沈軍団マモランティス所属。"], officialName: "軍団副官サブブカ", source: "6章 ヴァイガルド防衛線 3節" },
    { id: "M22", name: "メンドーサ", type: "メギド", isMajor: true, hints: ["不沈軍団マモランティス所属。"], officialName: "侵略魔兵メンドーサ", source: "6章 ヴァイガルド防衛線 3節" },
    { id: "M23", name: "ツギガル", type: "メギド", isMajor: true, hints: ["不沈軍団マモランティス所属。"], officialName: "侵略魔兵ツギガル", source: "6章 ヴァイガルド防衛線 3節" },
    { id: "M24", name: "アキレテス", type: "メギド", isMajor: false, hints: ["不沈軍団マモランティス所属。"], officialName: "侵略魔兵アキレテス", source: "6章 ヴァイガルド防衛線 3節" },
    { id: "M25", name: "ボヤーク", type: "メギド", isMajor: false, hints: ["不沈軍団マモランティス所属。"], officialName: "侵略魔兵ボヤーク", source: "6章 ヴァイガルド防衛線 3節" },
    { id: "M26", name: "ケイカ", type: "メギド", isMajor: false, hints: ["不沈軍団マモランティス所属。"], officialName: "侵略魔兵ケイカ", source: "6章 ヴァイガルド防衛線 3節" },
    { id: "M27", name: "ナランゾン", type: "メギド", isMajor: false, hints: ["不沈軍団マモランティス所属。"], officialName: "侵略魔兵ナランゾン", source: "6章 ヴァイガルド防衛線 3節" },
    { id: "M28", name: "マラコーダ", type: "メギド", isMajor: true, hints: ["ヒュトギンの元上官。", "おそらく元ネタはダンテの「神曲」の悪魔"], officialName: "マラコーダ", source: "その交渉は平和のために (他3)" },
    { id: "M29", name: "カルカ", type: "メギド", isMajor: false, hints: [], officialName: "カルカ", source: "ヒュトギンキャラスト (他2)" },
    { id: "M30", name: "チリアット", type: "メギド", isMajor: true, hints: ["べバルやアバラムの元上官。", "バロールとは一時期同じ軍団にいた。", "おそらく元ネタはダンテの「神曲」の悪魔"], officialName: "チリアット", source: "見習い女王と筋肉の悪魔 (他4)" },
    { id: "M31", name: "シオハオ", type: "メギド", isMajor: true, hints: ["アスラフィルの監視役。", "リャナンシィとは子育て旅団が同じ。"], officialName: "シオハオ", source: "アスラフィルキャラスト (他1)" },
    { id: "M32", name: "イオド", type: "メギド", isMajor: true, hints: ["アクィエルと再戦の誓いをした。", "レナトゥスで魂を混ぜられた。", "おそらく元ネタはクトゥルフ神話"], officialName: "イオド", source: "魔獅子と聖女と吸血鬼 (他1)" },
    { id: "M33", name: "アザト", type: "メギド", isMajor: false, hints: ["おそらく元ネタはクトゥルフ神話"], officialName: "アザト", source: "アクィエルキャラスト" },
    { id: "M34", name: "ギガス", type: "メギド", isMajor: true, hints: ["死を招く邪本を著した。", "追放された。"], officialName: "ギガス", source: "死を招く邪本ギギガガス" },
    { id: "M35", name: "ウィチセ", type: "メギド", isMajor: true, hints: ["罵美優蛇総長。", "凍結特効攻撃をしてくる。", "戦闘不能の味方がいると攻撃力が上がる。"], officialName: "ウィチセ", source: "7章 メギドラル潜入 2節 (他4)" },
    { id: "M36", name: "ハヤイカ", type: "メギド", isMajor: true, hints: ["罵美優蛇所属。"], officialName: "ハヤイカ", source: "7章 メギドラル潜入 2節 (他4)" },
    { id: "M37", name: "クツロギン", type: "メギド", isMajor: true, hints: ["くつろいでいた。"], officialName: "クツロギン", source: "7章 メギドラル潜入 2節 (他2)" },
    { id: "M38", name: "タシード", type: "メギド", isMajor: false, hints: ["番魚はどうしたか尋ねた。"], officialName: "タシード", source: "7章 メギドラル潜入 2節 (他2)" },
    { id: "M39", name: "カイル", type: "メギド", isMajor: true, hints: ["罵美優蛇元副総長。", "全体化を全体化する。", "感電が有効。"], officialName: "カイル", source: "7章 メギドラル潜入 2節 (他6)" },
    { id: "M40", name: "バレリコ", type: "メギド", isMajor: false, hints: [], officialName: "バレリコ", source: "オリエンスキャラスト (他7)" },
    { id: "M41", name: "トリゲン", type: "メギド", isMajor: false, hints: [], officialName: "トリゲン", source: "オリエンスキャラスト (他7)" },
    { id: "M42", name: "ハンミー", type: "メギド", isMajor: false, hints: [], officialName: "ハンミー", source: "オリエンスキャラスト (他7)" },
    { id: "M43", name: "グンシー", type: "メギド", isMajor: false, hints: [], officialName: "参謀グンシー", source: "オリエンスキャラスト (他7)" },
    { id: "M44", name: "アタッカス", type: "メギド", isMajor: false, hints: [], officialName: "チリアット軍団アタッカス", source: "オリエンスキャラスト" },
    { id: "M45", name: "カバウス", type: "メギド", isMajor: false, hints: [], officialName: "チリアット軍団カバウス", source: "オリエンスキャラスト" },
    { id: "M46", name: "ベロバッカ", type: "メギド", isMajor: false, hints: ["ニスロク、オリエンスの元上官。"], officialName: "軍団長ベロバッカ", source: "美味礼讃ノ魔宴 前編 (他2)" },
    { id: "M47", name: "ホルン", type: "メギド", isMajor: true, hints: ["ゲートを拡張する能力をもつ。", "励起で連続攻撃してくる。"], officialName: "ホルン", source: "7章 メギドラル潜入 3節" },
    { id: "M256", name: "クダクター", type: "メギド", isMajor: false, hints: ["ホルンと一緒にゲート拡張をしていた。", "励起で連続攻撃してくる。"], officialName: "クダクター", source: "ホルンの取り巻き" },
    { id: "M257", name: "ケズリナ", type: "メギド", isMajor: false, hints: ["ホルンと一緒にゲート拡張をしていた。", "励起で連続攻撃してくる。"], officialName: "ケズリナ", source: "ホルンの取り巻き" },
    { id: "M48", name: "アッキピテル", type: "メギド", isMajor: true, hints: ["バラムの元部下。", "牙の内海を巡る戦いで中央側の軍団長だった。", "おそらく元ネタはラテン語で「鷹」。"], officialName: "アッキピテル", source: "7章 メギドラル潜入 3節" },
    { id: "M49", name: "カドワッカ", type: "メギド", isMajor: false, hints: [], officialName: "カドワッカ", source: "ニバスBキャラスト" },
    { id: "M50", name: "サライ", type: "メギド", isMajor: false, hints: [], officialName: "サライ", source: "ニバスBキャラスト" },
    { id: "M51", name: "リモウム", type: "メギド", isMajor: false, hints: ["リビコの部下。", "寄生メギドの研究成果を盗もうとした。", "寄生メギドに魂を喰われ死亡した。"], officialName: "リモウム", source: "サタナキアBキャラスト (他1)" },
    { id: "M52", name: "ブライ", type: "メギド", isMajor: false, hints: ["リビコの部下。", "寄生メギドアナキスの研究をしていた。", "アシュレイに殺された。"], officialName: "ブライ", source: "サタナキアBキャラスト (他1)" },
    { id: "M53", name: "アブナ", type: "メギド", isMajor: false, hints: ["リビコの部下。", "寄生メギドアナキスの研究をしていた。", "虫の生態に関心を持っていた。"], officialName: "アブナ", source: "サタナキアBキャラスト (他1)" },
    { id: "M54", name: "リャナンシィ", type: "メギド", isMajor: true, hints: ["ガンコナーの弟子。", "寄生虫幻獣パラジスを使用した。", "おそらく元ネタはアイルランドの妖精。"], officialName: "リャナンシィ", source: "師の想い、弟子の想い" },
    { id: "M55", name: "ガンコナー", type: "メギド", isMajor: true, hints: ["フルフルにおいしいを教えた。", "寄生幻獣パラジスを発見した。", "おそらく元ネタはアイルランドの妖精。"], officialName: "ガンコナー", source: "師の想い、弟子の想い (他1)" },
    { id: "M56", name: "ハイザーン", type: "メギド", isMajor: false, hints: [], officialName: "軍団長ハイザーン", source: "フルフルCキャラスト" },
    { id: "M57", name: "イメーツ", type: "メギド", isMajor: false, hints: [], officialName: "副官イメーツ", source: "フルフルCキャラスト" },
    { id: "M58", name: "カナッゾ", type: "メギド", isMajor: false, hints: ["おそらく元ネタはダンテの「神曲」の悪魔"], officialName: "軍団長カナッゾ", source: "フルフルCキャラスト" },
    { id: "M59", name: "ザリチェ", type: "メギド", isMajor: false, hints: ["医療メギド。", "ユフィールの知人。", "おそらく元ネタは元ネタはゾロアスター教"], officialName: "ザリチェ", source: "ユフィールCキャラスト" },
    { id: "M60", name: "ドゥルジ", type: "メギド", isMajor: false, hints: ["おそらく元ネタは元ネタはゾロアスター教"], officialName: "ドゥルジ", source: "ユフィールCキャラスト" },
    { id: "M61", name: "リコレッキ", type: "メギド", isMajor: true, hints: [], officialName: "リコレッキ", source: "8章 第三計画 1節" },
    { id: "M62", name: "テガツメ", type: "メギド", isMajor: true, hints: ["手が爪っぽい。"], officialName: "侵略兵テガツメ", source: "不死の幻獣と失いし過去" },
    { id: "M63", name: "アカゲイ", type: "メギド", isMajor: true, hints: ["赤毛っぽい。"], officialName: "侵略兵アカゲイ", source: "不死の幻獣と失いし過去" },
    { id: "M64", name: "ボッチキス", type: "メギド", isMajor: false, hints: [], officialName: "ボッチキス", source: "8章 第三計画 2節" },
    { id: "M65", name: "ムオデル", type: "メギド", isMajor: false, hints: [], officialName: "ムオデル", source: "知の幻獣と悲しき対話 (他1)" },
    { id: "M66", name: "ブリナ", type: "メギド", isMajor: false, hints: [], officialName: "ブリナ", source: "知の幻獣と悲しき対話 (他1)" },
    { id: "M67", name: "ストレピ", type: "メギド", isMajor: false, hints: [], officialName: "ストレピ", source: "ダンタリオンRキャラスト" },
    { id: "M68", name: "ロンガ", type: "メギド", isMajor: false, hints: [], officialName: "ロンガ", source: "ダンタリオンRキャラスト" },
    { id: "M69", name: "ゲケン", type: "メギド", isMajor: false, hints: [], officialName: "ゲケン", source: "ダンタリオンRキャラスト" },
    { id: "M70", name: "イステッカ", type: "メギド", isMajor: false, hints: [], officialName: "イステッカ", source: "ダンタリオンRキャラスト" },
    { id: "M71", name: "コスーイ", type: "メギド", isMajor: false, hints: [], officialName: "コスーイ", source: "ベヒモスBキャラスト" },
    { id: "M72", name: "モンジーン", type: "メギド", isMajor: false, hints: [], officialName: "モンジーン", source: "カジノ！―勝利の方程式― (他1)" },
    { id: "M73", name: "スプリット", type: "メギド", isMajor: false, hints: [], officialName: "「カジノ」幹部スプリット", source: "カジノ！―勝利の方程式―" },
    { id: "M74", name: "メリディアナ", type: "メギド", isMajor: false, hints: ["「カジノ」軍団長となった", "幻獣体の名前はシルヴェステ", "おそらく元ネタは「宮廷人の閑話」"], officialName: "メリディアナ", source: "カジノ！―勝利の方程式―" },
    { id: "M75", name: "テゴワーイ", type: "メギド", isMajor: false, hints: [], officialName: "テゴワーイ", source: "グザファンキャラスト" },
    { id: "M76", name: "タクラーム", type: "メギド", isMajor: false, hints: [], officialName: "タクラーム", source: "グザファンキャラスト" },
    { id: "M77", name: "ソート", type: "メギド", isMajor: false, hints: [], officialName: "「カジノ」構成員ソート", source: "ミノソンキャラスト" },
    { id: "M78", name: "ウーマ", type: "メギド", isMajor: false, hints: [], officialName: "「カジノ」構成員ウーマ", source: "ミノソンキャラスト" },
    { id: "M79", name: "インガセクト", type: "メギド", isMajor: true, hints: ["マモン親衛隊。", "使者ごときの分際で上に立とうとした。", "最大HPの30％以下のダメージを無効化する。"], officialName: "インガセクト", source: "8章 第三計画 3節 (他1)" },
    { id: "M80", name: "ホーコック", type: "メギド", isMajor: false, hints: ["マモン親衛隊。"], officialName: "ホーコック", source: "8章 第三計画 3節 (他1)" },
    { id: "M81", name: "サンシタン", type: "メギド", isMajor: false, hints: [], officialName: "サンシタン", source: "暴走児バラキエル！" },
    { id: "M82", name: "アヤトゥール", type: "メギド", isMajor: false, hints: [], officialName: "アヤトゥール", source: "暴走児バラキエル！" },
    { id: "M83", name: "グローシタ", type: "メギド", isMajor: false, hints: [], officialName: "グローシタ", source: "暴走児バラキエル！" },
    { id: "M84", name: "オーメニミル", type: "メギド", isMajor: false, hints: [], officialName: "軍団長オーメニミル", source: "暴走児バラキエル！ (他1)" },
    { id: "M85", name: "タイガンニール", type: "メギド", isMajor: true, hints: ["マモン親衛隊。", "防御力が高く、防御依存攻撃もしてくる。", "対岸にいる。　星間の塔にもいる。"], officialName: "タイガンニール", source: "8章 第三計画 4節 (他3)" },
    { id: "M86", name: "テッキトゥ", type: "メギド", isMajor: false, hints: [], officialName: "テッキトゥ", source: "マモンキャラスト" },
    { id: "M87", name: "トークス", type: "メギド", isMajor: false, hints: [], officialName: "トークス", source: "マモンキャラスト" },
    { id: "M88", name: "マテヨン", type: "メギド", isMajor: false, hints: [], officialName: "議会の騎士マテヨン", source: "メギドラルの悲劇の騎士" },
    { id: "M89", name: "リリィ", type: "メギド", isMajor: false, hints: ["夢見の者。"], officialName: "リリィ", source: "メギドラルの悲劇の騎士" },
    { id: "M90", name: "リリモ", type: "メギド", isMajor: false, hints: ["夢見の者。"], officialName: "リリモ", source: "メギドラルの悲劇の騎士" },
    { id: "M91", name: "リリア", type: "メギド", isMajor: false, hints: ["夢見の者。"], officialName: "リリア", source: "メギドラルの悲劇の騎士" },
    { id: "M92", name: "リリエ", type: "メギド", isMajor: false, hints: ["夢見の者。"], officialName: "リリエ", source: "メギドラルの悲劇の騎士" },
    { id: "M93", name: "ナブール", type: "メギド", isMajor: false, hints: ["懲罰局所属。"], officialName: "ナブール", source: "恋は拷問、愛は処刑" },
    { id: "M94", name: "モノバゾス", type: "メギド", isMajor: false, hints: [], officialName: "モノバゾス", source: "そして灯火は静かに消える" },
    { id: "M95", name: "ジェヴォーダン", type: "メギド", isMajor: true, hints: [], officialName: "ジェヴォーダン", source: "そして灯火は静かに消える" },
    { id: "M96", name: "ケーダシン", type: "メギド", isMajor: true, hints: [], officialName: "ケーダシン", source: "9章 懲罰局壊滅 1節 (他1)" },
    { id: "M97", name: "オーシェ", type: "メギド", isMajor: false, hints: [], officialName: "オーシェ", source: "プルソンBキャラスト (他1)" },
    { id: "M98", name: "ヨゴシ", type: "メギド", isMajor: false, hints: [], officialName: "ヨゴシ", source: "プルソンBキャラスト" },
    { id: "M99", name: "マセタン", type: "メギド", isMajor: true, hints: ["フライナイツ所属。", "キーキーという幻獣を相棒にしていた。", "怒闘を展開しバーサークする。"], officialName: "マセタン", source: "プルソンBキャラスト (他1)" },
    { id: "M100", name: "トゥゲッチ", type: "メギド", isMajor: false, hints: [], officialName: "トゥゲッチ", source: "プルソンBキャラスト" },
    { id: "M101", name: "コマルゼイ", type: "メギド", isMajor: false, hints: [], officialName: "コマルゼイくん", source: "プルソンBキャラスト" },
    { id: "M102", name: "シナナイン", type: "メギド", isMajor: true, hints: ["フライナイツ所属。", "取り巻きが生きている間は死なない。"], officialName: "シナナイン", source: "プルソンBキャラスト (他1)" },
    { id: "M103", name: "クレンチン", type: "メギド", isMajor: false, hints: [], officialName: "クレンチン", source: "この手にかつての栄光を" },
    { id: "M104", name: "ダイダロス", type: "メギド", isMajor: false, hints: [], officialName: "ダイダロス", source: "この手にかつての栄光を (他1)" },
    { id: "M105", name: "ウボム", type: "メギド", isMajor: false, hints: [], officialName: "軍団長ウボム", source: "ブリフォーキャラスト" },
    { id: "M106", name: "サンボーン", type: "メギド", isMajor: false, hints: [], officialName: "サンボーン", source: "ブリフォーキャラスト" },
    { id: "M107", name: "ノーキン", type: "メギド", isMajor: false, hints: [], officialName: "ノーキン", source: "ブリフォーキャラスト" },
    { id: "M108", name: "ヨワキム", type: "メギド", isMajor: false, hints: [], officialName: "ヨワキム", source: "ブリフォーキャラスト" },
    { id: "M109", name: "ソレナリィ", type: "メギド", isMajor: false, hints: [], officialName: "ソレナリィ", source: "ブリフォーキャラスト" },
    { id: "M110", name: "ソコソッコ", type: "メギド", isMajor: false, hints: [], officialName: "ソコソッコ", source: "ブリフォーキャラスト" },
    { id: "M111", name: "メガイー", type: "メギド", isMajor: false, hints: [], officialName: "メガイー", source: "ブリフォーキャラスト" },
    { id: "M112", name: "コザイク", type: "メギド", isMajor: false, hints: [], officialName: "軍団長コザイク", source: "ブリフォーキャラスト" },
    { id: "M113", name: "ヤブレカブレ", type: "メギド", isMajor: true, hints: [], officialName: "ヤブレカブレ", source: "9章 懲罰局壊滅 2節 (他1)" },
    { id: "M114", name: "サイゼン", type: "メギド", isMajor: false, hints: [], officialName: "サイゼン", source: "9章 懲罰局壊滅 2節 (他1)" },
    { id: "M115", name: "ザミエル", type: "メギド", isMajor: false, hints: ["おそらく元ネタは「魔弾の射手」の悪魔"], officialName: "ザミエル", source: "トーア公御前試合" },
    { id: "M116", name: "ウゴーノシュ", type: "メギド", isMajor: false, hints: [], officialName: "ウゴーノシュ", source: "トーア公御前試合" },
    { id: "M117", name: "ヒトカラゲ", type: "メギド", isMajor: false, hints: [], officialName: "ヒトカラゲ", source: "トーア公御前試合" },
    { id: "M118", name: "メサジェ", type: "メギド", isMajor: false, hints: [], officialName: "メサジェ", source: "変わる心、変わらぬ心" },
    { id: "M119", name: "エスピオン", type: "メギド", isMajor: false, hints: [], officialName: "エスピオン", source: "変わる心、変わらぬ心 (他2)" },
    { id: "M120", name: "コローシャ", type: "メギド", isMajor: false, hints: [], officialName: "コローシャ", source: "変わる心、変わらぬ心" },
    { id: "M121", name: "アッサシ", type: "メギド", isMajor: false, hints: [], officialName: "アッサシ", source: "変わる心、変わらぬ心" },
    { id: "M122", name: "ラギル", type: "メギド", isMajor: false, hints: [], officialName: "ラギル", source: "変わる心、変わらぬ心 (他1)" },
    { id: "M123", name: "ニーガス", type: "メギド", isMajor: false, hints: [], officialName: "ニーガス", source: "変わる心、変わらぬ心 (他1)" },
    { id: "M124", name: "ガーディ", type: "メギド", isMajor: false, hints: [], officialName: "ガーディ", source: "アロケルRキャラスト" },
    { id: "M125", name: "コゴトン", type: "メギド", isMajor: false, hints: [], officialName: "コゴトン", source: "其は素晴らしき戦士の器 (他1)" },
    { id: "M126", name: "オキタエル", type: "メギド", isMajor: false, hints: [], officialName: "オキタエル", source: "険しく長き筋肉の道！" },
    { id: "M127", name: "プルトン", type: "メギド", isMajor: true, hints: ["異世界侵攻作戦総指揮官。", "元夢見の者。", "おそらく元ネタはローマ神話"], officialName: "プルトン", source: "9章 懲罰局壊滅 3節 (他10)" },
    { id: "M128", name: "グウィルギィ", type: "メギド", isMajor: true, hints: ["ワイルド・ハントの副官。"], officialName: "グウィルギィ", source: "WILD HUNT 前編 獣たちの集う場所 (他2)" },
    { id: "M129", name: "エルドラコ", type: "メギド", isMajor: false, hints: ["ワイルド・ハントの軍団長。"], officialName: "エルドラコ", source: "WILD HUNT 前編 獣たちの集う場所 (他2)" },
    { id: "M130", name: "ハズサーン", type: "メギド", isMajor: false, hints: [], officialName: "ハズサーン", source: "WILD HUNT 前編 獣たちの集う場所 (他2)" },
    { id: "M131", name: "ツガエル", type: "メギド", isMajor: false, hints: [], officialName: "ツガエル", source: "WILD HUNT 前編 獣たちの集う場所 (他2)" },
    { id: "M132", name: "カカルドゥ", type: "メギド", isMajor: false, hints: [], officialName: "カカルドゥ", source: "WILD HUNT 前編 獣たちの集う場所 (他1)" },
    { id: "M133", name: "イコロス", type: "メギド", isMajor: false, hints: [], officialName: "イコロス", source: "WILD HUNT 前編 獣たちの集う場所 (他2)" },
    { id: "M134", name: "ギョフノリィ", type: "メギド", isMajor: false, hints: [], officialName: "議会の騎士ギョフノリィ", source: "WILD HUNT 前編 獣たちの集う場所" },
    { id: "M135", name: "セイロンダガー", type: "メギド", isMajor: false, hints: [], officialName: "軍団長セイロンダガー", source: "ゲイボルグキャラスト" },
    { id: "M136", name: "バントー", type: "メギド", isMajor: false, hints: [], officialName: "バントー", source: "商売人たちのブルース" },
    { id: "M137", name: "グレシャム", type: "メギド", isMajor: true, hints: ["おそらく元ネタは経済学の法則"], officialName: "グレシャム", source: "商売人たちのブルース (他1)" },
    { id: "M138", name: "ドコミテン", type: "メギド", isMajor: false, hints: [], officialName: "ドコミテン", source: "商売人たちのブルース" },
    { id: "M139", name: "ダレヤネン", type: "メギド", isMajor: false, hints: [], officialName: "ダレヤネン", source: "商売人たちのブルース" },
    { id: "M140", name: "テダイ", type: "メギド", isMajor: false, hints: [], officialName: "テダイ", source: "商売人たちのブルース (他1)" },
    { id: "M141", name: "オードル", type: "メギド", isMajor: false, hints: [], officialName: "オードル", source: "9章 懲罰局壊滅 4節" },
    { id: "M142", name: "トーミル", type: "メギド", isMajor: false, hints: [], officialName: "トーミル", source: "9章 懲罰局壊滅 4節" },
    { id: "M143", name: "ネブカドネザル", type: "メギド", isMajor: false, hints: [], officialName: "ネブカドネザル", source: "復讐の悪魔と怨讐の魔人" },
    { id: "M144", name: "コシチェイ", type: "メギド", isMajor: true, hints: ["あるペクスに名前を奪われた。", "おそらく元ネタはスラヴ神話"], officialName: "コシチェイ", source: "アリオクキャラスト" },
    { id: "M145", name: "ポベートール", type: "メギド", isMajor: false, hints: [], officialName: "ポベートール", source: "君はもう、1人じゃない" },
    { id: "M146", name: "ファルファレロ", type: "メギド", isMajor: false, hints: ["おそらく元ネタはダンテの「神曲」の悪魔"], officialName: "ファルファレロ", source: "君はもう、1人じゃない" },
    { id: "M147", name: "エリク", type: "メギド", isMajor: false, hints: [], officialName: "エリク", source: "不死者バエルの切なる願い" },
    { id: "M148", name: "ムチャリンダ", type: "メギド", isMajor: true, hints: ["おそらく元ネタはインド神話"], officialName: "軍団長ムチャリンダ", source: "その優しさに意味がある (他8)" },
    { id: "M149", name: "ギリメカラ", type: "メギド", isMajor: true, hints: ["おそらく元ネタはスリランカ・インド神話"], officialName: "ギリメカラ", source: "彼の者、東方より来たり (他11)" },
    { id: "M150", name: "マガツヒ", type: "メギド", isMajor: true, hints: ["おそらく元ネタは日本神話"], officialName: "マガツヒ", source: "彼の者、東方より来たり (他11)" },
    { id: "M151", name: "オズワリ", type: "メギド", isMajor: false, hints: ["議席管理官。", "セメルーゼの友人。"], officialName: "オズワリ", source: "10章 マグナ・レギオ 2節 (他1)" },
    { id: "M152", name: "イキリオー", type: "メギド", isMajor: true, hints: ["バチクソ撃破団の軍団長。"], officialName: "英雄イキリオー", source: "10章 マグナ・レギオ 2節 (他1)" },
    { id: "M153", name: "ドローヌマン", type: "メギド", isMajor: false, hints: ["ヘドロドロップの軍団長。"], officialName: "ドローヌマン団長", source: "10章 マグナ・レギオ 2節" },
    { id: "M154", name: "アツメラルダ", type: "メギド", isMajor: false, hints: [], officialName: "軍団長アツメラルダ", source: "10章 マグナ・レギオ 2節" },
    { id: "M155", name: "カタギ", type: "メギド", isMajor: false, hints: [], officialName: "カタギ", source: "10章 マグナ・レギオ 2節 (他3)" },
    { id: "M156", name: "ワレェ", type: "メギド", isMajor: false, hints: [], officialName: "ワレェ", source: "10章 マグナ・レギオ 2節 (他3)" },
    { id: "M157", name: "ニクー", type: "メギド", isMajor: false, hints: [], officialName: "ニクー軍団長", source: "10章 マグナ・レギオ 2節 (他1)" },
    { id: "M158", name: "ダンセ", type: "メギド", isMajor: false, hints: [], officialName: "ダンセ副長", source: "10章 マグナ・レギオ 2節" },
    { id: "M159", name: "シャドウギャクソン", type: "メギド", isMajor: false, hints: [], officialName: "シャドウ・ギャクソン", source: "10章 マグナ・レギオ 2節 (他2)" },
    { id: "M160", name: "インシュウ", type: "メギド", isMajor: false, hints: [], officialName: "インシュウ", source: "10章 マグナ・レギオ 2節 (他2)" },
    { id: "M161", name: "ムーメン", type: "メギド", isMajor: false, hints: [], officialName: "ムーメン", source: "10章 マグナ・レギオ 2節" },
    { id: "M162", name: "スマホミー", type: "メギド", isMajor: false, hints: [], officialName: "スマホミー", source: "10章 マグナ・レギオ 2節" },
    { id: "M163", name: "アオリウンデ", type: "メギド", isMajor: false, hints: [], officialName: "アオリウンデ", source: "10章 マグナ・レギオ 2節 (他2)" },
    { id: "M164", name: "ミマモラー", type: "メギド", isMajor: false, hints: [], officialName: "ミマモラー", source: "10章 マグナ・レギオ 2節" },
    { id: "M165", name: "マッカーセイル", type: "メギド", isMajor: false, hints: ["リバイバイルをプロセルピナに任せた。"], officialName: "マッカーセイル", source: "10章 マグナ・レギオ 2節 (他1)" },
    { id: "M166", name: "リバイバイル", type: "メギド", isMajor: true, hints: [], officialName: "リバイバイル", source: "10章 マグナ・レギオ 2節 (他10)" },
    { id: "M167", name: "トメラニアン", type: "メギド", isMajor: false, hints: [], officialName: "トメラニアン副団長", source: "10章 マグナ・レギオ 2節 (他3)" },
    { id: "M168", name: "トビー", type: "メギド", isMajor: false, hints: [], officialName: "トビー軍団長", source: "10章 マグナ・レギオ 2節 (他4)" },
    { id: "M169", name: "ハッタリッパー", type: "メギド", isMajor: false, hints: [], officialName: "ハッタリッパー", source: "10章 マグナ・レギオ 2節" },
    { id: "M170", name: "シーネ", type: "メギド", isMajor: false, hints: [], officialName: "シーネ", source: "10章 マグナ・レギオ 2節 (他1)" },
    { id: "M171", name: "オムカ", type: "メギド", isMajor: false, hints: [], officialName: "オムカ", source: "10章 マグナ・レギオ 2節" },
    { id: "M172", name: "ネガティ", type: "メギド", isMajor: false, hints: ["総司令アルマロス配下のゲストレイス軍団の副団長。"], officialName: "ネガティ", source: "10章 マグナ・レギオ 2節 (他2)" },
    { id: "M173", name: "ズルコワルコ", type: "メギド", isMajor: true, hints: ["拒絶区画の中で物品を配っていた。", "妄戦ちゃんの知人。"], officialName: "ズルコワルコ", source: "10章 マグナ・レギオ 2節 (他1)" },
    { id: "M174", name: "モドリー", type: "メギド", isMajor: false, hints: [], officialName: "モドリー", source: "10章 マグナ・レギオ 2節" },
    { id: "M175", name: "シルバホン", type: "メギド", isMajor: false, hints: ["おそらく元ネタは「西遊記」"], officialName: "シルバホン", source: "継承せし者たち (他5)" },
    { id: "M176", name: "タイガーセンポ", type: "メギド", isMajor: true, hints: ["おそらく元ネタは「西遊記」"], officialName: "タイガーセンポ", source: "継承せし者たち (他7)" },
    { id: "M177", name: "ゲストレイス", type: "メギド", isMajor: true, hints: ["総司令アルマロス配下の軍団長。"], officialName: "ゲストレイス", source: "10章 マグナ・レギオ 3節 ステージ103 (他9)" },
    { id: "M178", name: "プロセルピナ", type: "メギド", isMajor: true, hints: ["メギド８魔星の一人。", "儚い。", "おそらく元ネタはギリシャ神話"], officialName: "プロセルピナ", source: "10章 マグナ・レギオ 3節 ステージ104 (他11)" },
    { id: "M179", name: "ダイオーン", type: "メギド", isMajor: false, hints: [], officialName: "軍団長ダイオーン", source: "閉ざされた世界の中で" },
    { id: "M180", name: "モンゴール", type: "メギド", isMajor: false, hints: [], officialName: "副官モンゴール", source: "閉ざされた世界の中で" },
    { id: "M181", name: "ウェンディゴ", type: "メギド", isMajor: true, hints: ["おそらく元ネタは北アメリカ伝承"], officialName: "ウェンディゴ", source: "When'd he go into there？" },
    { id: "M182", name: "ゼッコロ", type: "メギド", isMajor: false, hints: [], officialName: "ゼッコロ", source: "アスモデウスRキャラスト" },
    { id: "M183", name: "ゴルドホン", type: "メギド", isMajor: false, hints: ["おそらく元ネタは「西遊記」"], officialName: "ゴルドホン", source: "艶なる狐、夢のまにまに (他3)" },
    { id: "M184", name: "センコック", type: "メギド", isMajor: false, hints: [], officialName: "センコック", source: "信頼と可能性" },
    { id: "M185", name: "コーサラウ", type: "メギド", isMajor: false, hints: [], officialName: "コーサラウ", source: "信頼と可能性" },
    { id: "M186", name: "ワラベトール", type: "メギド", isMajor: false, hints: [], officialName: "ワラベトール", source: "信頼と可能性" },
    { id: "M187", name: "ニューカマ", type: "メギド", isMajor: false, hints: [], officialName: "ニューカマ", source: "ウァラクCキャラスト" },
    { id: "M188", name: "シーニア", type: "メギド", isMajor: false, hints: [], officialName: "シーニア", source: "ウァラクCキャラスト" },
    { id: "M189", name: "オネスト", type: "メギド", isMajor: false, hints: [], officialName: "オネスト", source: "ウァラクCキャラスト" },
    { id: "M190", name: "ボヤクーナ", type: "メギド", isMajor: false, hints: [], officialName: "ボヤクーナ", source: "グレモリーRキャラスト" },
    { id: "M191", name: "デスガ", type: "メギド", isMajor: false, hints: [], officialName: "デスガ", source: "グレモリーRキャラスト" },
    { id: "M192", name: "ロックロー", type: "メギド", isMajor: false, hints: [], officialName: "ロック・ロー", source: "龍馬相搏、腥風不已 (他1)" },
    { id: "M193", name: "ヒットバン", type: "メギド", isMajor: false, hints: [], officialName: "ヒットバン", source: "龍馬相搏、腥風不已 (他1)" },
    { id: "M194", name: "ペナンガラン", type: "メギド", isMajor: false, hints: [], officialName: "ペナンガラン", source: "龍馬相搏、腥風不已 (他1)" },
    { id: "M195", name: "ラーフ", type: "メギド", isMajor: false, hints: [], officialName: "ラーフ", source: "龍馬相搏、腥風不已 (他1)" },
    { id: "M196", name: "ファンブラン", type: "メギド", isMajor: false, hints: [], officialName: "ファンブラン", source: "11章 激動のメギドラル 1節 ステージ109" },
    { id: "M197", name: "ボロボロス", type: "メギド", isMajor: false, hints: [], officialName: "ボロボロス", source: "ソロモン王の日常・春" },
    { id: "M198", name: "レオナール", type: "メギド", isMajor: true, hints: ["フライナイツ所属。", "整った。", "地獄の辞典にその名前の記載がある。"], officialName: "レオナール", source: "11章 激動のメギドラル 1節 ステージ110 (他8)" },
    { id: "M199", name: "ニョイフレッシュ", type: "メギド", isMajor: true, hints: ["モレクの腹心。総参謀長。", "おそらく元ネタは「西遊記」"], officialName: "ニョイフレッシュ", source: "吼えよ、カクリヨの白い虎 (他6)" },
    { id: "M200", name: "コスカライオン", type: "メギド", isMajor: false, hints: [], officialName: "コスカライオン", source: "吼えよ、カクリヨの白い虎 (他1)" },
    { id: "M201", name: "ザコイヤ", type: "メギド", isMajor: false, hints: [], officialName: "ザコイヤ", source: "11章 激動のメギドラル 1節 ステージ111" },
    { id: "M202", name: "ウニノセール", type: "メギド", isMajor: false, hints: [], officialName: "ウニノセール", source: "真味、ただこれ淡なれば" },
    { id: "M203", name: "トリフマゼンタ", type: "メギド", isMajor: false, hints: [], officialName: "トリフマゼンタ", source: "真味、ただこれ淡なれば" },
    { id: "M204", name: "アブラポス", type: "メギド", isMajor: false, hints: [], officialName: "アブラポス", source: "真味、ただこれ淡なれば" },
    { id: "M205", name: "ショッパイン", type: "メギド", isMajor: false, hints: [], officialName: "ショッパイン", source: "真味、ただこれ淡なれば" },
    { id: "M206", name: "ホイクイーン", type: "メギド", isMajor: false, hints: [], officialName: "ホイクイーン", source: "11章 激動のメギドラル 2節 ステージ112" },
    { id: "M207", name: "ストゥム", type: "メギド", isMajor: true, hints: ["フライナイツ所属のイレーザー。", "幻獣を介して妖蛆と接触できる。"], officialName: "ストゥム", source: "11章 激動のメギドラル 2節 ステージ112" },
    { id: "M208", name: "ケノックス", type: "メギド", isMajor: false, hints: [], officialName: "ケノックス", source: "ソロモン王の日常・夏" },
    { id: "M209", name: "ショックジョー", type: "メギド", isMajor: false, hints: [], officialName: "ショック・ジョー", source: "ソロモン王の日常・夏" },
    { id: "M210", name: "セプテントリオン", type: "メギド", isMajor: true, hints: ["かつてオリエンスのライバル的存在だった。", "狙撃銃を扱い遠距離からの攻撃を得意とする。", "おそらく元ネタはラテン語で「北斗七星」"], officialName: "セプテントリオン", source: "銃と私とあいつとそいつ" },
    { id: "M211", name: "スジトゥス", type: "メギド", isMajor: false, hints: [], officialName: "スジトゥス", source: "銃と私とあいつとそいつ" },
    { id: "M212", name: "ギリガティ", type: "メギド", isMajor: false, hints: [], officialName: "副官ギリガティ", source: "銃と私とあいつとそいつ" },
    { id: "M213", name: "デミウルゴス", type: "メギド", isMajor: true, hints: ["イレーサーと８魔星により倒された。", "おそらく元ネタはプラトンの「ティマイオス」"], officialName: "デミウルゴス", source: "11章 激動のメギドラル 2節 ステージ113 (他6)" },
    { id: "M214", name: "チャラケル", type: "メギド", isMajor: false, hints: [], officialName: "チャラケル", source: "オリエンスBキャラスト" },
    { id: "M215", name: "インフム", type: "メギド", isMajor: false, hints: [], officialName: "インフム", source: "オリエンスBキャラスト" },
    { id: "M216", name: "ラッカン", type: "メギド", isMajor: false, hints: [], officialName: "ラッカン", source: "オリエンスBキャラスト" },
    { id: "M217", name: "ガルデニング", type: "メギド", isMajor: true, hints: [], officialName: "ガルデニング", source: "食べて育てて分け合って" },
    { id: "M218", name: "オハナヴァタケ", type: "メギド", isMajor: false, hints: [], officialName: "オハナヴァタケ", source: "食べて育てて分け合って" },
    { id: "M219", name: "ヴィニルハウズ", type: "メギド", isMajor: false, hints: [], officialName: "ヴィニルハウズ", source: "食べて育てて分け合って" },
    { id: "M220", name: "ファナティッカ", type: "メギド", isMajor: false, hints: [], officialName: "ファナティッカ", source: "11章 激動のメギドラル 3節 ステージ115" },
    { id: "M221", name: "リリル", type: "メギド", isMajor: false, hints: [], officialName: "夢見のリリル", source: "それは、逃れ得ぬ呪縛 (他2)" },
    { id: "M222", name: "サラウンピョウ", type: "メギド", isMajor: false, hints: [], officialName: "サラウンピョウ", source: "それは、逃れ得ぬ呪縛" },
    { id: "M223", name: "モノシリィ", type: "メギド", isMajor: false, hints: [], officialName: "モノシリィ", source: "母と子と、おかーさんと" },
    { id: "M224", name: "クイークェグ", type: "メギド", isMajor: false, hints: ["おそらく元ネタは「白鯨」"], officialName: "クイークェグ", source: "母と子と、おかーさんと" },
    { id: "M225", name: "イシュメール", type: "メギド", isMajor: false, hints: ["おそらく元ネタは「白鯨」"], officialName: "イシュメール", source: "母と子と、おかーさんと" },
    { id: "M226", name: "エイハブ", type: "メギド", isMajor: true, hints: ["おそらく元ネタは「白鯨」"], officialName: "エイハブ", source: "母と子と、おかーさんと" },
    { id: "M227", name: "スターバック", type: "メギド", isMajor: true, hints: ["おそらく元ネタは「白鯨」"], officialName: "スターバック", source: "母と子と、おかーさんと" },
    { id: "M228", name: "タシュテゴ", type: "メギド", isMajor: false, hints: ["おそらく元ネタは「白鯨」"], officialName: "タシュテゴ", source: "母と子と、おかーさんと" },
    { id: "M229", name: "クジョコ", type: "メギド", isMajor: false, hints: [], officialName: "クジョコ", source: "ソロモン王の日常・冬" },
    { id: "M230", name: "クサムシュリ", type: "メギド", isMajor: false, hints: ["人間牧場の管理者メギド。"], officialName: "クサムシュリ", source: "11章 激動のメギドラル 4節 ステージ118" },
    { id: "M231", name: "モーニゲル", type: "メギド", isMajor: false, hints: [], officialName: "モーニゲル", source: "11章 激動のメギドラル 4節 ステージ120" },
    { id: "M232", name: "マモリキレン", type: "メギド", isMajor: false, hints: [], officialName: "防衛隊長マモリキレン", source: "帰らばや、我が故郷へ" },
    { id: "M233", name: "トンデーン", type: "メギド", isMajor: false, hints: [], officialName: "トンデーン", source: "帰らばや、我が故郷へ" },
    { id: "M234", name: "カイタック", type: "メギド", isMajor: false, hints: [], officialName: "カイタック", source: "帰らばや、我が故郷へ" },
    { id: "M235", name: "ラプラス", type: "メギド", isMajor: true, hints: ["追放メギド。", "記憶を読む能力があった。", "おそらく元ネタは決定論。"], officialName: "ラプラス", source: "12章 そして世界が生まれる 1節 ステージ121 (他1)" },
    { id: "M236", name: "ヤヌス", type: "メギド", isMajor: true, hints: ["追放メギド。", "時間遡行ゲートを発見し、利用した。", "おそらく元ネタはローマ神話"], officialName: "ヤヌス", source: "12章 そして世界が生まれる 1節 ステージ121 (他2)" },
    { id: "M237", name: "ムコイコカ", type: "メギド", isMajor: false, hints: ["ダムロックをサタンの元まで案内した。"], officialName: "ムコイコカ", source: "12章 そして世界が生まれる 1節 ステージ122 (他1)" },
    { id: "M238", name: "アザメザラク", type: "メギド", isMajor: false, hints: [], officialName: "アザメザラク", source: "ソロモン王と呪いの人形" },
    { id: "M239", name: "タスケネイ", type: "メギド", isMajor: false, hints: [], officialName: "タスケネイ", source: "サタンキャラスト" },
    { id: "M240", name: "ゴルディン", type: "メギド", isMajor: false, hints: [], officialName: "ゴルディン", source: "12章 そして世界が生まれる 2節 ステージ125" },
    { id: "M241", name: "パイロキシアン", type: "メギド", isMajor: true, hints: [], officialName: "パイロキシアン", source: "12章 そして世界が生まれる 2節 ステージ126" },
    { id: "M242", name: "イクサシタ", type: "メギド", isMajor: false, hints: [], officialName: "イクサシタ", source: "12章 そして世界が生まれる 3節 ステージ127" },
    { id: "M243", name: "ニューリアン", type: "メギド", isMajor: false, hints: [], officialName: "ニューリアン", source: "12章 そして世界が生まれる 3節 ステージ128 (他1)" },
    { id: "M244", name: "シンクシング", type: "メギド", isMajor: false, hints: [], officialName: "シンクシング", source: "12章 そして世界が生まれる 3節 ステージ128 (他1)" },
    { id: "M245", name: "ヤルーゼ", type: "メギド", isMajor: false, hints: [], officialName: "ヤルーゼ", source: "12章 そして世界が生まれる 3節 ステージ128 (他1)" },
    { id: "M246", name: "オレンスバイ", type: "メギド", isMajor: false, hints: [], officialName: "オレンスバイ", source: "12章 そして世界が生まれる 3節 ステージ129" },
    { id: "M247", name: "モードリタイン", type: "メギド", isMajor: false, hints: [], officialName: "モードリタイン", source: "エピローグ" },
    { id: "M248", name: "ムボーダン", type: "メギド", isMajor: true, hints: ["二手に分かれても二倍頑張れば互角であると説いた。"], officialName: "ムボーダン（脳筋参謀）", source: "脳筋参謀メギド" },
    { id: "M249", name: "アルスノヴァ", type: "メギド", isMajor: true, hints: ["エルダーとなった。"], officialName: "アルス・ノヴァ", source: "エルダー" },
    { id: "M250", name: "エリダヌス", type: "メギド", isMajor: true, hints: ["かつて存在したとされ、６体の兵器のもとになった。", "おそらく現在は死亡している。"], officialName: "エリダヌス", source: "ザウラクたちの元になったメギド" },
    { id: "M251", name: "ヒュプノス", type: "メギド", isMajor: false, hints: [], officialName: "ヒュプノス", source: "11章 激動のメギドラル 3節 ステージ117" },
    { id: "M252", name: "メギラオン", type: "メギド", isMajor: false, hints: ["黒い犬。ナンバー002。"], officialName: "メギラオン", source: "サタンの取り巻き　００２" },
    { id: "M253", name: "トリギラン", type: "メギド", isMajor: false, hints: ["黒い犬。ナンバー003。"], officialName: "トリギラン", source: "サタンの取り巻き　００３" },
    { id: "M254", name: "アノウノン", type: "メギド", isMajor: true, hints: ["ぺクスにフォトンバーストした。"], officialName: "アノウノン", source: "メインクエスト・ステージ118" },
    { id: "M255", name: "アカマル", type: "メギド", isMajor: true, hints: ["ゲートを守っていた。"], officialName: "アカマル", source: "メインクエスト・ステージ8" },
    { id: "M256", name: "バーバヤガ", type: "メギド", isMajor: false, hints: ["南の理術研究院の長。", "おそらく元ネタはスラヴ民話"], officialName: "バーバヤガ", source: "" },
    { id: "H1", name: "ガブリエル", type: "ハルマ", isMajor: true, hints: ["ハルマである。"], officialName: "ガブリエル", source: "1章 辺境の剣 (他52)" },
    { id: "H2", name: "カマエル", type: "ハルマ", isMajor: true, hints: ["ハルマである。"], officialName: "カマエル", source: "2章 王都の盾 (他46)" },
    { id: "H3", name: "ミカエル", type: "ハルマ", isMajor: true, hints: ["ハルマである。"], officialName: "ミカエル", source: "3章 赤い月 (他16)" },
    { id: "H4", name: "コロスエル", type: "ハルマ", isMajor: true, hints: ["ハルマである。", "メギドラル攻撃隊所属。"], officialName: "コロスエル", source: "10章 マグナ・レギオ 3節 ステージ105" },
    { id: "H5", name: "ヨリソエル", type: "ハルマ", isMajor: false, hints: [], officialName: "ヨリソエル", source: "10章 マグナ・レギオ 3節 ステージ105 (他6)" },
    { id: "H6", name: "パットキエル", type: "ハルマ", isMajor: true, hints: ["ハルマである。", "コロスエルの僚機。"], officialName: "パットキエル", source: "10章 マグナ・レギオ 3節 ステージ105" },
    { id: "H7", name: "ジットタエル", type: "ハルマ", isMajor: true, hints: ["ハルマである。", "コロスエルの僚機。"], officialName: "ジットタエル", source: "10章 マグナ・レギオ 3節 ステージ105" },
    { id: "H8", name: "テレルエル", type: "ハルマ", isMajor: false, hints: [], officialName: "テレルエル", source: "10章 マグナ・レギオ 3節 ステージ105" },
    { id: "H9", name: "キガエル", type: "ハルマ", isMajor: false, hints: ["騎士団に化けてメギド72を監視していたが、バレて着替えた。"], officialName: "キガエル", source: "10章 マグナ・レギオ 3節 ステージ105 (他1)" },
    { id: "H10", name: "デテキエル", type: "ハルマ", isMajor: false, hints: [], officialName: "デテキエル", source: "10章 マグナ・レギオ 3節 ステージ105 (他1)" },
    { id: "H11", name: "フセギエル", type: "ハルマ", isMajor: false, hints: [], officialName: "フセギエル", source: "10章 マグナ・レギオ 4節 ステージ106" },
    { id: "H12", name: "スナッフエル", type: "ハルマ", isMajor: true, hints: ["ハルマである。"], officialName: "スナッフエル", source: "10章 マグナ・レギオ 4節 ステージ106" },
    { id: "H13", name: "サイコエル", type: "ハルマ", isMajor: false, hints: [], officialName: "サイコエル", source: "10章 マグナ・レギオ 4節 ステージ106 (他1)" },
    { id: "H14", name: "マテヨエル", type: "ハルマ", isMajor: true, hints: ["ハルマである。"], officialName: "マテヨエル", source: "10章 マグナ・レギオ 4節 ステージ106" },
    { id: "H15", name: "トラエル", type: "ハルマ", isMajor: false, hints: [], officialName: "トラエル", source: "アスモデウスRキャラスト" },
    { id: "H16", name: "ツタエル", type: "ハルマ", isMajor: false, hints: [], officialName: "ツタエル", source: "アスモデウスRキャラスト" },
    { id: "H17", name: "カゾエル", type: "ハルマ", isMajor: false, hints: [], officialName: "カゾエル", source: "アスモデウスRキャラスト" },
    { id: "H18", name: "タネウエル", type: "ハルマ", isMajor: false, hints: [], officialName: "タネウエル", source: "10章 マグナ・レギオ 4節 ステージ107" },
    { id: "H19", name: "イモフエル", type: "ハルマ", isMajor: false, hints: [], officialName: "イモフエル", source: "10章 マグナ・レギオ 4節 ステージ107" },
    { id: "H20", name: "ナベニエル", type: "ハルマ", isMajor: true, hints: ["ハルマである。"], officialName: "ナベニエル", source: "10章 マグナ・レギオ 4節 ステージ107" },
    { id: "H21", name: "アタマサエル", type: "ハルマ", isMajor: false, hints: [], officialName: "アタマサエル", source: "10章 マグナ・レギオ 4節 ステージ107" },
    { id: "H22", name: "ジンジャエル", type: "ハルマ", isMajor: true, hints: ["ハルマである。"], officialName: "ジンジャエル", source: "10章 マグナ・レギオ 4節 ステージ107" },
    { id: "H23", name: "シーゴッドオエル", type: "ハルマ", isMajor: true, hints: ["ハルマである。"], officialName: "シーゴッドオエル", source: "10章 マグナ・レギオ 4節 ステージ107 (他4)" },
    { id: "H24", name: "チャーリーデカエル", type: "ハルマ", isMajor: false, hints: ["名前が長すぎるので使用しない。"], officialName: "チャーリーデカエル", source: "10章 マグナ・レギオ 4節 ステージ107" },
    { id: "H25", name: "メッシクーエル", type: "ハルマ", isMajor: false, hints: [], officialName: "メッシクーエル", source: "10章 マグナ・レギオ 4節 ステージ107 (他1)" },
    { id: "H26", name: "フローネルエル", type: "ハルマ", isMajor: false, hints: [], officialName: "フローネルエル", source: "10章 マグナ・レギオ 4節 ステージ107" },
    { id: "H27", name: "ウテヌエル", type: "ハルマ", isMajor: false, hints: [], officialName: "ウテヌエル", source: "10章 マグナ・レギオ 4節 ステージ108" },
    { id: "H28", name: "マサカエル", type: "ハルマ", isMajor: true, hints: ["ハルマである。"], officialName: "マサカエル", source: "11章 激動のメギドラル 1節 ステージ111 (他1)" },
    { id: "H29", name: "モーカエル", type: "ハルマ", isMajor: true, hints: ["ハルマである。"], officialName: "モーカエル", source: "11章 激動のメギドラル 2節 ステージ113 (他4)" },
    { id: "H30", name: "マイゴエル", type: "ハルマ", isMajor: false, hints: [], officialName: "マイゴエル", source: "11章 激動のメギドラル 2節 ステージ113 (他2)" },
    { id: "H31", name: "ツカマエル", type: "ハルマ", isMajor: false, hints: [], officialName: "ツカマエル", source: "11章 激動のメギドラル 2節 ステージ113 (他3)" },
    { id: "H32", name: "ヨクミエル", type: "ハルマ", isMajor: false, hints: [], officialName: "ヨクミエル", source: "12章 そして世界が生まれる 1節 ステージ121 (他2)" },
    { id: "H33", name: "イマナライエル", type: "ハルマ", isMajor: true, hints: ["ハルマである。"], officialName: "イマナライエル", source: "12章 そして世界が生まれる 2節 ステージ124 (他1)" },
    { id: "H34", name: "ウタガエル", type: "ハルマ", isMajor: false, hints: [], officialName: "ウタガエル", source: "12章 そして世界が生まれる 3節 ステージ127" },
    { id: "H35", name: "カンガエル", type: "ハルマ", isMajor: false, hints: [], officialName: "カンガエル", source: "12章 そして世界が生まれる 3節 ステージ127" },
    { id: "H36", name: "マチガエル", type: "ハルマ", isMajor: false, hints: [], officialName: "マチガエル", source: "8魔星モレク、参戦" },
    { id: "H37", name: "マダタタカエル", type: "ハルマ", isMajor: false, hints: [], officialName: "マダタタカエル", source: "8魔星モレク、参戦" },
    { id: "H38", name: "ヒックリカエル", type: "ハルマ", isMajor: false, hints: [], officialName: "ヒックリカエル", source: "8魔星モレク、参戦" },
    { id: "H39", name: "サガシエル", type: "ハルマ", isMajor: false, hints: [], officialName: "サガシエル", source: "エピローグ" },
    { id: "H40", name: "ラジエル", type: "ハルマ", isMajor: true, hints: ["ハルマである。"], officialName: "ラジエル", source: "エピローグ" }
];
